/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getPostApiAccountDynamicClaimsRefreshUrl = () => {


  

  return `/api/account/dynamic-claims/refresh`
}

export const postApiAccountDynamicClaimsRefresh = async ( options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getPostApiAccountDynamicClaimsRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostApiAccountDynamicClaimsRefreshMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>, TError,void, TContext> => {

const mutationKey = ['postApiAccountDynamicClaimsRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>, void> = () => {
          

          return  postApiAccountDynamicClaimsRefresh(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountDynamicClaimsRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>>
    
    export type PostApiAccountDynamicClaimsRefreshMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiAccountDynamicClaimsRefresh = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountDynamicClaimsRefresh>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostApiAccountDynamicClaimsRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    