/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiIdentityUsersIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const putApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiIdentityUsersIdBodyUserNameMin = 0;
export const putApiIdentityUsersIdBodyUserNameMax = 256;

export const putApiIdentityUsersIdBodyNameMin = 0;
export const putApiIdentityUsersIdBodyNameMax = 64;

export const putApiIdentityUsersIdBodySurnameMin = 0;
export const putApiIdentityUsersIdBodySurnameMax = 64;

export const putApiIdentityUsersIdBodyEmailMin = 0;
export const putApiIdentityUsersIdBodyEmailMax = 256;

export const putApiIdentityUsersIdBodyPhoneNumberMin = 0;
export const putApiIdentityUsersIdBodyPhoneNumberMax = 16;

export const putApiIdentityUsersIdBodyPasswordMin = 0;
export const putApiIdentityUsersIdBodyPasswordMax = 128;



export const putApiIdentityUsersIdBody = zod.object({
  "userName": zod.string().min(putApiIdentityUsersIdBodyUserNameMin).max(putApiIdentityUsersIdBodyUserNameMax),
  "name": zod.string().min(putApiIdentityUsersIdBodyNameMin).max(putApiIdentityUsersIdBodyNameMax).nullish(),
  "surname": zod.string().min(putApiIdentityUsersIdBodySurnameMin).max(putApiIdentityUsersIdBodySurnameMax).nullish(),
  "email": zod.email().min(putApiIdentityUsersIdBodyEmailMin).max(putApiIdentityUsersIdBodyEmailMax),
  "phoneNumber": zod.string().min(putApiIdentityUsersIdBodyPhoneNumberMin).max(putApiIdentityUsersIdBodyPhoneNumberMax).nullish(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "roleNames": zod.array(zod.string()).nullish(),
  "password": zod.string().min(putApiIdentityUsersIdBodyPasswordMin).max(putApiIdentityUsersIdBodyPasswordMax).nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const putApiIdentityUsersIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const deleteApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiIdentityUsersQuerySkipCountMin = 0;
export const getApiIdentityUsersQuerySkipCountMax = 2147483647;

export const getApiIdentityUsersQueryMaxResultCountMax = 2147483647;



export const getApiIdentityUsersQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.number().min(getApiIdentityUsersQuerySkipCountMin).max(getApiIdentityUsersQuerySkipCountMax).optional(),
  "MaxResultCount": zod.number().min(1).max(getApiIdentityUsersQueryMaxResultCountMax).optional(),
  "ExtraProperties": zod.record(zod.string(), zod.unknown()).optional()
})

export const getApiIdentityUsersResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})).nullish(),
  "totalCount": zod.number().optional()
})

export const postApiIdentityUsersBodyUserNameMin = 0;
export const postApiIdentityUsersBodyUserNameMax = 256;

export const postApiIdentityUsersBodyNameMin = 0;
export const postApiIdentityUsersBodyNameMax = 64;

export const postApiIdentityUsersBodySurnameMin = 0;
export const postApiIdentityUsersBodySurnameMax = 64;

export const postApiIdentityUsersBodyEmailMin = 0;
export const postApiIdentityUsersBodyEmailMax = 256;

export const postApiIdentityUsersBodyPhoneNumberMin = 0;
export const postApiIdentityUsersBodyPhoneNumberMax = 16;

export const postApiIdentityUsersBodyPasswordMin = 0;
export const postApiIdentityUsersBodyPasswordMax = 128;



export const postApiIdentityUsersBody = zod.object({
  "userName": zod.string().min(postApiIdentityUsersBodyUserNameMin).max(postApiIdentityUsersBodyUserNameMax),
  "name": zod.string().min(postApiIdentityUsersBodyNameMin).max(postApiIdentityUsersBodyNameMax).nullish(),
  "surname": zod.string().min(postApiIdentityUsersBodySurnameMin).max(postApiIdentityUsersBodySurnameMax).nullish(),
  "email": zod.email().min(postApiIdentityUsersBodyEmailMin).max(postApiIdentityUsersBodyEmailMax),
  "phoneNumber": zod.string().min(postApiIdentityUsersBodyPhoneNumberMin).max(postApiIdentityUsersBodyPhoneNumberMax).nullish(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "roleNames": zod.array(zod.string()).nullish(),
  "password": zod.string().min(postApiIdentityUsersBodyPasswordMin).max(postApiIdentityUsersBodyPasswordMax)
})

export const postApiIdentityUsersResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const getApiIdentityUsersByIdIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiIdentityUsersByIdIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const getApiIdentityUsersIdRolesParams = zod.object({
  "id": zod.uuid()
})

export const getApiIdentityUsersIdRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})).nullish()
})

export const putApiIdentityUsersIdRolesParams = zod.object({
  "id": zod.uuid()
})

export const putApiIdentityUsersIdRolesBody = zod.object({
  "roleNames": zod.array(zod.string())
})

export const getApiIdentityUsersAssignableRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})).nullish()
})

export const getApiIdentityUsersByUsernameUserNameParams = zod.object({
  "userName": zod.string()
})

export const getApiIdentityUsersByUsernameUserNameResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const getApiIdentityUsersByEmailEmailParams = zod.object({
  "email": zod.string()
})

export const getApiIdentityUsersByEmailEmailResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

