/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiIdentityUsersIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

export const PutApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiIdentityUsersIdBodyUserNameMin = 0;
export const putApiIdentityUsersIdBodyUserNameMax = 256;

export const putApiIdentityUsersIdBodyNameMin = 0;
export const putApiIdentityUsersIdBodyNameMax = 64;

export const putApiIdentityUsersIdBodySurnameMin = 0;
export const putApiIdentityUsersIdBodySurnameMax = 64;

export const putApiIdentityUsersIdBodyEmailMin = 0;
export const putApiIdentityUsersIdBodyEmailMax = 256;

export const putApiIdentityUsersIdBodyPhoneNumberMin = 0;
export const putApiIdentityUsersIdBodyPhoneNumberMax = 16;

export const putApiIdentityUsersIdBodyPasswordMin = 0;
export const putApiIdentityUsersIdBodyPasswordMax = 128;



export const PutApiIdentityUsersIdBody = zod.object({
  "userName": zod.string().min(putApiIdentityUsersIdBodyUserNameMin).max(putApiIdentityUsersIdBodyUserNameMax),
  "name": zod.string().min(putApiIdentityUsersIdBodyNameMin).max(putApiIdentityUsersIdBodyNameMax).nullish(),
  "surname": zod.string().min(putApiIdentityUsersIdBodySurnameMin).max(putApiIdentityUsersIdBodySurnameMax).nullish(),
  "email": zod.email().min(putApiIdentityUsersIdBodyEmailMin).max(putApiIdentityUsersIdBodyEmailMax),
  "phoneNumber": zod.string().min(putApiIdentityUsersIdBodyPhoneNumberMin).max(putApiIdentityUsersIdBodyPhoneNumberMax).nullish(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "roleNames": zod.array(zod.string()).nullish(),
  "password": zod.string().min(putApiIdentityUsersIdBodyPasswordMin).max(putApiIdentityUsersIdBodyPasswordMax).nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const PutApiIdentityUsersIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

export const DeleteApiIdentityUsersIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiIdentityUsersIdResponse = zod.unknown()

export const getApiIdentityUsersQuerySkipCountMin = 0;
export const getApiIdentityUsersQuerySkipCountMax = 2147483647;

export const getApiIdentityUsersQueryMaxResultCountMax = 2147483647;



export const GetApiIdentityUsersQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.int().min(getApiIdentityUsersQuerySkipCountMin).max(getApiIdentityUsersQuerySkipCountMax).optional(),
  "MaxResultCount": zod.int().min(1).max(getApiIdentityUsersQueryMaxResultCountMax).optional(),
  "ExtraProperties": zod.record(zod.string(), zod.unknown()).optional()
})

export const GetApiIdentityUsersResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})).nullish(),
  "totalCount": zod.int().optional()
})

export const postApiIdentityUsersBodyUserNameMin = 0;
export const postApiIdentityUsersBodyUserNameMax = 256;

export const postApiIdentityUsersBodyNameMin = 0;
export const postApiIdentityUsersBodyNameMax = 64;

export const postApiIdentityUsersBodySurnameMin = 0;
export const postApiIdentityUsersBodySurnameMax = 64;

export const postApiIdentityUsersBodyEmailMin = 0;
export const postApiIdentityUsersBodyEmailMax = 256;

export const postApiIdentityUsersBodyPhoneNumberMin = 0;
export const postApiIdentityUsersBodyPhoneNumberMax = 16;

export const postApiIdentityUsersBodyPasswordMin = 0;
export const postApiIdentityUsersBodyPasswordMax = 128;



export const PostApiIdentityUsersBody = zod.object({
  "userName": zod.string().min(postApiIdentityUsersBodyUserNameMin).max(postApiIdentityUsersBodyUserNameMax),
  "name": zod.string().min(postApiIdentityUsersBodyNameMin).max(postApiIdentityUsersBodyNameMax).nullish(),
  "surname": zod.string().min(postApiIdentityUsersBodySurnameMin).max(postApiIdentityUsersBodySurnameMax).nullish(),
  "email": zod.email().min(postApiIdentityUsersBodyEmailMin).max(postApiIdentityUsersBodyEmailMax),
  "phoneNumber": zod.string().min(postApiIdentityUsersBodyPhoneNumberMin).max(postApiIdentityUsersBodyPhoneNumberMax).nullish(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "roleNames": zod.array(zod.string()).nullish(),
  "password": zod.string().min(postApiIdentityUsersBodyPasswordMin).max(postApiIdentityUsersBodyPasswordMax)
})

export const PostApiIdentityUsersResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

export const GetApiIdentityUsersByIdIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiIdentityUsersByIdIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

export const GetApiIdentityUsersIdRolesParams = zod.object({
  "id": zod.uuid()
})

export const GetApiIdentityUsersIdRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})).nullish()
})

export const PutApiIdentityUsersIdRolesParams = zod.object({
  "id": zod.uuid()
})

export const PutApiIdentityUsersIdRolesBody = zod.object({
  "roleNames": zod.array(zod.string())
})

export const PutApiIdentityUsersIdRolesResponse = zod.unknown()

export const GetApiIdentityUsersAssignableRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})).nullish()
})

export const GetApiIdentityUsersByUsernameUserNameParams = zod.object({
  "userName": zod.string()
})

export const GetApiIdentityUsersByUsernameUserNameResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

export const GetApiIdentityUsersByEmailEmailParams = zod.object({
  "email": zod.string()
})

export const GetApiIdentityUsersByEmailEmailResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({"offset":true}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({"offset":true}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({"offset":true}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.int().optional(),
  "lockoutEnd": zod.iso.datetime({"offset":true}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.int().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({"offset":true}).nullish()
})

