/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiMultiTenancyTenantsParams,
  PagedResultDtoOfTenantDto,
  PutApiMultiTenancyTenantsIdDefaultConnectionStringParams,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpTenantManagementTenantCreateDto,
  VoloAbpTenantManagementTenantDto,
  VoloAbpTenantManagementTenantUpdateDto
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetApiMultiTenancyTenantsIdUrl = (id: string,) => {




  return `/api/multi-tenancy/tenants/${id}`
}

export const getApiMultiTenancyTenantsId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpTenantManagementTenantDto> => {

  return abpMutator<VoloAbpTenantManagementTenantDto>(getGetApiMultiTenancyTenantsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiMultiTenancyTenantsIdQueryKey = (id: string,) => {
    return [
    `/api/multi-tenancy/tenants/${id}`
    ] as const;
    }


export const getGetApiMultiTenancyTenantsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMultiTenancyTenantsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>> = ({ signal }) => getApiMultiTenancyTenantsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMultiTenancyTenantsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>>
export type GetApiMultiTenancyTenantsIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiMultiTenancyTenantsId<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenantsId<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenantsId<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMultiTenancyTenantsId<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMultiTenancyTenantsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutApiMultiTenancyTenantsIdUrl = (id: string,) => {




  return `/api/multi-tenancy/tenants/${id}`
}

export const putApiMultiTenancyTenantsId = async (id: string,
    voloAbpTenantManagementTenantUpdateDto?: NonReadonly<VoloAbpTenantManagementTenantUpdateDto>, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpTenantManagementTenantDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpTenantManagementTenantDto>(getPutApiMultiTenancyTenantsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpTenantManagementTenantUpdateDto)
  }
);}





export const getPutApiMultiTenancyTenantsIdMutationKey = () => ['putApiMultiTenancyTenantsId'] as const;

export const getPutApiMultiTenancyTenantsIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>, TError,PutApiMultiTenancyTenantsIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>, TError,PutApiMultiTenancyTenantsIdMutationVariables, TContext> => {

const mutationKey = getPutApiMultiTenancyTenantsIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>, PutApiMultiTenancyTenantsIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiMultiTenancyTenantsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiMultiTenancyTenantsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>>
    export type PutApiMultiTenancyTenantsIdMutationBody = NonReadonly<VoloAbpTenantManagementTenantUpdateDto> | undefined
    export type PutApiMultiTenancyTenantsIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PutApiMultiTenancyTenantsIdMutationVariables = {id: string;data?: NonReadonly<VoloAbpTenantManagementTenantUpdateDto>}

    export const usePutApiMultiTenancyTenantsId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>, TError,PutApiMultiTenancyTenantsIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiMultiTenancyTenantsId>>,
        TError,
        PutApiMultiTenancyTenantsIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiMultiTenancyTenantsIdMutationOptions(options), queryClient);
    }
    export const getDeleteApiMultiTenancyTenantsIdUrl = (id: string,) => {




  return `/api/multi-tenancy/tenants/${id}`
}

export const deleteApiMultiTenancyTenantsId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

  return abpMutator<void>(getDeleteApiMultiTenancyTenantsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiMultiTenancyTenantsIdMutationKey = () => ['deleteApiMultiTenancyTenantsId'] as const;

export const getDeleteApiMultiTenancyTenantsIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>, TError,DeleteApiMultiTenancyTenantsIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>, TError,DeleteApiMultiTenancyTenantsIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiMultiTenancyTenantsIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>, DeleteApiMultiTenancyTenantsIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiMultiTenancyTenantsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMultiTenancyTenantsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>>

    export type DeleteApiMultiTenancyTenantsIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type DeleteApiMultiTenancyTenantsIdMutationVariables = {id: string}

    export const useDeleteApiMultiTenancyTenantsId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>, TError,DeleteApiMultiTenancyTenantsIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsId>>,
        TError,
        DeleteApiMultiTenancyTenantsIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiMultiTenancyTenantsIdMutationOptions(options), queryClient);
    }
    export const getGetApiMultiTenancyTenantsUrl = (params?: GetApiMultiTenancyTenantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/multi-tenancy/tenants?${stringifiedParams}` : `/api/multi-tenancy/tenants`
}

export const getApiMultiTenancyTenants = async (params?: GetApiMultiTenancyTenantsParams, options?: Parameters<typeof abpMutator>[1]): Promise<PagedResultDtoOfTenantDto> => {

  return abpMutator<PagedResultDtoOfTenantDto>(getGetApiMultiTenancyTenantsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiMultiTenancyTenantsQueryKey = (params?: GetApiMultiTenancyTenantsParams,) => {
    return [
    `/api/multi-tenancy/tenants`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiMultiTenancyTenantsQueryOptions = <TData = Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiMultiTenancyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMultiTenancyTenantsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>> = ({ signal }) => getApiMultiTenancyTenants(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMultiTenancyTenantsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>>
export type GetApiMultiTenancyTenantsQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiMultiTenancyTenants<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiMultiTenancyTenantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenants<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiMultiTenancyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenants>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenants<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiMultiTenancyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMultiTenancyTenants<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiMultiTenancyTenantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenants>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMultiTenancyTenantsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostApiMultiTenancyTenantsUrl = () => {




  return `/api/multi-tenancy/tenants`
}

export const postApiMultiTenancyTenants = async (voloAbpTenantManagementTenantCreateDto?: NonReadonly<VoloAbpTenantManagementTenantCreateDto>, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpTenantManagementTenantDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpTenantManagementTenantDto>(getPostApiMultiTenancyTenantsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpTenantManagementTenantCreateDto)
  }
);}





export const getPostApiMultiTenancyTenantsMutationKey = () => ['postApiMultiTenancyTenants'] as const;

export const getPostApiMultiTenancyTenantsMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMultiTenancyTenants>>, TError,PostApiMultiTenancyTenantsMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMultiTenancyTenants>>, TError,PostApiMultiTenancyTenantsMutationVariables, TContext> => {

const mutationKey = getPostApiMultiTenancyTenantsMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMultiTenancyTenants>>, PostApiMultiTenancyTenantsMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiMultiTenancyTenants(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMultiTenancyTenantsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMultiTenancyTenants>>>
    export type PostApiMultiTenancyTenantsMutationBody = NonReadonly<VoloAbpTenantManagementTenantCreateDto> | undefined
    export type PostApiMultiTenancyTenantsMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiMultiTenancyTenantsMutationVariables = {data?: NonReadonly<VoloAbpTenantManagementTenantCreateDto>}

    export const usePostApiMultiTenancyTenants = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMultiTenancyTenants>>, TError,PostApiMultiTenancyTenantsMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMultiTenancyTenants>>,
        TError,
        PostApiMultiTenancyTenantsMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiMultiTenancyTenantsMutationOptions(options), queryClient);
    }
    export const getGetApiMultiTenancyTenantsIdDefaultConnectionStringUrl = (id: string,) => {




  return `/api/multi-tenancy/tenants/${id}/default-connection-string`
}

export const getApiMultiTenancyTenantsIdDefaultConnectionString = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<string> => {

  return abpMutator<string>(getGetApiMultiTenancyTenantsIdDefaultConnectionStringUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiMultiTenancyTenantsIdDefaultConnectionStringQueryKey = (id: string,) => {
    return [
    `/api/multi-tenancy/tenants/${id}/default-connection-string`
    ] as const;
    }


export const getGetApiMultiTenancyTenantsIdDefaultConnectionStringQueryOptions = <TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiMultiTenancyTenantsIdDefaultConnectionStringQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>> = ({ signal }) => getApiMultiTenancyTenantsIdDefaultConnectionString(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiMultiTenancyTenantsIdDefaultConnectionStringQueryResult = NonNullable<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>>
export type GetApiMultiTenancyTenantsIdDefaultConnectionStringQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiMultiTenancyTenantsIdDefaultConnectionString<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenantsIdDefaultConnectionString<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>,
          TError,
          Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiMultiTenancyTenantsIdDefaultConnectionString<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiMultiTenancyTenantsIdDefaultConnectionString<TData = Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiMultiTenancyTenantsIdDefaultConnectionString>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiMultiTenancyTenantsIdDefaultConnectionStringQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutApiMultiTenancyTenantsIdDefaultConnectionStringUrl = (id: string,
    params?: PutApiMultiTenancyTenantsIdDefaultConnectionStringParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/multi-tenancy/tenants/${id}/default-connection-string?${stringifiedParams}` : `/api/multi-tenancy/tenants/${id}/default-connection-string`
}

export const putApiMultiTenancyTenantsIdDefaultConnectionString = async (id: string,
    params?: PutApiMultiTenancyTenantsIdDefaultConnectionStringParams, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

  return abpMutator<void>(getPutApiMultiTenancyTenantsIdDefaultConnectionStringUrl(id,params),
  {
    ...options,
    method: 'PUT'


  }
);}





export const getPutApiMultiTenancyTenantsIdDefaultConnectionStringMutationKey = () => ['putApiMultiTenancyTenantsIdDefaultConnectionString'] as const;

export const getPutApiMultiTenancyTenantsIdDefaultConnectionStringMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext> => {

const mutationKey = getPutApiMultiTenancyTenantsIdDefaultConnectionStringMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>, PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables> = (props) => {
          const {id,params} = props ?? {};

          return  putApiMultiTenancyTenantsIdDefaultConnectionString(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationResult = NonNullable<Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>>

    export type PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables = {id: string;params?: PutApiMultiTenancyTenantsIdDefaultConnectionStringParams}

    export const usePutApiMultiTenancyTenantsIdDefaultConnectionString = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiMultiTenancyTenantsIdDefaultConnectionString>>,
        TError,
        PutApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiMultiTenancyTenantsIdDefaultConnectionStringMutationOptions(options), queryClient);
    }
    export const getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringUrl = (id: string,) => {




  return `/api/multi-tenancy/tenants/${id}/default-connection-string`
}

export const deleteApiMultiTenancyTenantsIdDefaultConnectionString = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

  return abpMutator<void>(getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationKey = () => ['deleteApiMultiTenancyTenantsIdDefaultConnectionString'] as const;

export const getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext> => {

const mutationKey = getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>, DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiMultiTenancyTenantsIdDefaultConnectionString(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>>

    export type DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables = {id: string}

    export const useDeleteApiMultiTenancyTenantsIdDefaultConnectionString = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>, TError,DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMultiTenancyTenantsIdDefaultConnectionString>>,
        TError,
        DeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiMultiTenancyTenantsIdDefaultConnectionStringMutationOptions(options), queryClient);
    }
