/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiMultiTenancyTenantsIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const putApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiMultiTenancyTenantsIdBodyNameMin = 0;
export const putApiMultiTenancyTenantsIdBodyNameMax = 64;



export const putApiMultiTenancyTenantsIdBody = zod.object({
  "name": zod.string().min(putApiMultiTenancyTenantsIdBodyNameMin).max(putApiMultiTenancyTenantsIdBodyNameMax),
  "concurrencyStamp": zod.string().nullish()
})

export const putApiMultiTenancyTenantsIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const deleteApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiMultiTenancyTenantsQuerySkipCountMin = 0;
export const getApiMultiTenancyTenantsQuerySkipCountMax = 2147483647;

export const getApiMultiTenancyTenantsQueryMaxResultCountMax = 2147483647;



export const getApiMultiTenancyTenantsQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.number().min(getApiMultiTenancyTenantsQuerySkipCountMin).max(getApiMultiTenancyTenantsQuerySkipCountMax).optional(),
  "MaxResultCount": zod.number().min(1).max(getApiMultiTenancyTenantsQueryMaxResultCountMax).optional()
})

export const getApiMultiTenancyTenantsResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})).nullish(),
  "totalCount": zod.number().optional()
})

export const postApiMultiTenancyTenantsBodyNameMin = 0;
export const postApiMultiTenancyTenantsBodyNameMax = 64;

export const postApiMultiTenancyTenantsBodyAdminEmailAddressMax = 256;

export const postApiMultiTenancyTenantsBodyAdminPasswordMax = 128;



export const postApiMultiTenancyTenantsBody = zod.object({
  "name": zod.string().min(postApiMultiTenancyTenantsBodyNameMin).max(postApiMultiTenancyTenantsBodyNameMax),
  "adminEmailAddress": zod.email().min(1).max(postApiMultiTenancyTenantsBodyAdminEmailAddressMax),
  "adminPassword": zod.string().min(1).max(postApiMultiTenancyTenantsBodyAdminPasswordMax)
})

export const postApiMultiTenancyTenantsResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const getApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

export const getApiMultiTenancyTenantsIdDefaultConnectionStringResponse = zod.string()

export const putApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

export const putApiMultiTenancyTenantsIdDefaultConnectionStringQueryParams = zod.object({
  "defaultConnectionString": zod.string().optional()
})

export const deleteApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

