/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiMultiTenancyTenantsIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const PutApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiMultiTenancyTenantsIdBodyNameMin = 0;
export const putApiMultiTenancyTenantsIdBodyNameMax = 64;



export const PutApiMultiTenancyTenantsIdBody = zod.object({
  "name": zod.string().min(putApiMultiTenancyTenantsIdBodyNameMin).max(putApiMultiTenancyTenantsIdBodyNameMax),
  "concurrencyStamp": zod.string().nullish()
})

export const PutApiMultiTenancyTenantsIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const DeleteApiMultiTenancyTenantsIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiMultiTenancyTenantsIdResponse = zod.unknown()

export const getApiMultiTenancyTenantsQuerySkipCountMin = 0;
export const getApiMultiTenancyTenantsQuerySkipCountMax = 2147483647;

export const getApiMultiTenancyTenantsQueryMaxResultCountMax = 2147483647;



export const GetApiMultiTenancyTenantsQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.int().min(getApiMultiTenancyTenantsQuerySkipCountMin).max(getApiMultiTenancyTenantsQuerySkipCountMax).optional(),
  "MaxResultCount": zod.int().min(1).max(getApiMultiTenancyTenantsQueryMaxResultCountMax).optional()
})

export const GetApiMultiTenancyTenantsResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})).nullish(),
  "totalCount": zod.int().optional()
})

export const postApiMultiTenancyTenantsBodyNameMin = 0;
export const postApiMultiTenancyTenantsBodyNameMax = 64;

export const postApiMultiTenancyTenantsBodyAdminEmailAddressMax = 256;

export const postApiMultiTenancyTenantsBodyAdminPasswordMax = 128;



export const PostApiMultiTenancyTenantsBody = zod.object({
  "name": zod.string().min(postApiMultiTenancyTenantsBodyNameMin).max(postApiMultiTenancyTenantsBodyNameMax),
  "adminEmailAddress": zod.email().min(1).max(postApiMultiTenancyTenantsBodyAdminEmailAddressMax),
  "adminPassword": zod.string().min(1).max(postApiMultiTenancyTenantsBodyAdminPasswordMax)
})

export const PostApiMultiTenancyTenantsResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const GetApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

export const GetApiMultiTenancyTenantsIdDefaultConnectionStringResponse = zod.string()

export const PutApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

export const PutApiMultiTenancyTenantsIdDefaultConnectionStringQueryParams = zod.object({
  "defaultConnectionString": zod.string().optional()
})

export const PutApiMultiTenancyTenantsIdDefaultConnectionStringResponse = zod.unknown()

export const DeleteApiMultiTenancyTenantsIdDefaultConnectionStringParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiMultiTenancyTenantsIdDefaultConnectionStringResponse = zod.unknown()

