/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiIdentityRolesAllResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})).nullish()
})

export const getApiIdentityRolesQuerySkipCountMin = 0;
export const getApiIdentityRolesQuerySkipCountMax = 2147483647;

export const getApiIdentityRolesQueryMaxResultCountMax = 2147483647;



export const GetApiIdentityRolesQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.int().min(getApiIdentityRolesQuerySkipCountMin).max(getApiIdentityRolesQuerySkipCountMax).optional(),
  "MaxResultCount": zod.int().min(1).max(getApiIdentityRolesQueryMaxResultCountMax).optional(),
  "ExtraProperties": zod.record(zod.string(), zod.unknown()).optional()
})

export const GetApiIdentityRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})).nullish(),
  "totalCount": zod.int().optional()
})

export const postApiIdentityRolesBodyNameMin = 0;
export const postApiIdentityRolesBodyNameMax = 256;



export const PostApiIdentityRolesBody = zod.object({
  "name": zod.string().min(postApiIdentityRolesBodyNameMin).max(postApiIdentityRolesBodyNameMax),
  "isDefault": zod.boolean().optional(),
  "isPublic": zod.boolean().optional()
})

export const PostApiIdentityRolesResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})

export const GetApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiIdentityRolesIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})

export const PutApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiIdentityRolesIdBodyNameMin = 0;
export const putApiIdentityRolesIdBodyNameMax = 256;



export const PutApiIdentityRolesIdBody = zod.object({
  "name": zod.string().min(putApiIdentityRolesIdBodyNameMin).max(putApiIdentityRolesIdBodyNameMax),
  "isDefault": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish()
})

export const PutApiIdentityRolesIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({"offset":true}).optional()
})

export const DeleteApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

export const DeleteApiIdentityRolesIdResponse = zod.unknown()

