/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiIdentityRolesAllResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})).nullish()
})

export const getApiIdentityRolesQuerySkipCountMin = 0;
export const getApiIdentityRolesQuerySkipCountMax = 2147483647;

export const getApiIdentityRolesQueryMaxResultCountMax = 2147483647;



export const getApiIdentityRolesQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.number().min(getApiIdentityRolesQuerySkipCountMin).max(getApiIdentityRolesQuerySkipCountMax).optional(),
  "MaxResultCount": zod.number().min(1).max(getApiIdentityRolesQueryMaxResultCountMax).optional(),
  "ExtraProperties": zod.record(zod.string(), zod.unknown()).optional()
})

export const getApiIdentityRolesResponse = zod.object({
  "items": zod.array(zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})).nullish(),
  "totalCount": zod.number().optional()
})

export const postApiIdentityRolesBodyNameMin = 0;
export const postApiIdentityRolesBodyNameMax = 256;



export const postApiIdentityRolesBody = zod.object({
  "name": zod.string().min(postApiIdentityRolesBodyNameMin).max(postApiIdentityRolesBodyNameMax),
  "isDefault": zod.boolean().optional(),
  "isPublic": zod.boolean().optional()
})

export const postApiIdentityRolesResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})

export const getApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiIdentityRolesIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})

export const putApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

export const putApiIdentityRolesIdBodyNameMin = 0;
export const putApiIdentityRolesIdBodyNameMax = 256;



export const putApiIdentityRolesIdBody = zod.object({
  "name": zod.string().min(putApiIdentityRolesIdBodyNameMin).max(putApiIdentityRolesIdBodyNameMax),
  "isDefault": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish()
})

export const putApiIdentityRolesIdResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "name": zod.string().nullish(),
  "isDefault": zod.boolean().optional(),
  "isStatic": zod.boolean().optional(),
  "isPublic": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish(),
  "creationTime": zod.iso.datetime({}).optional()
})

export const deleteApiIdentityRolesIdParams = zod.object({
  "id": zod.uuid()
})

