/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  VoloAbpAccountRegisterDto,
  VoloAbpAccountResetPasswordDto,
  VoloAbpAccountSendPasswordResetCodeDto,
  VoloAbpAccountVerifyPasswordResetTokenInput,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpIdentityIdentityUserDto
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getPostApiAccountRegisterUrl = () => {




  return `/api/account/register`
}

export const postApiAccountRegister = async (voloAbpAccountRegisterDto?: NonReadonly<VoloAbpAccountRegisterDto>, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpIdentityIdentityUserDto>(getPostApiAccountRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountRegisterDto)
  }
);}





export const getPostApiAccountRegisterMutationKey = () => ['postApiAccountRegister'] as const;

export const getPostApiAccountRegisterMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountRegister>>, TError,PostApiAccountRegisterMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountRegister>>, TError,PostApiAccountRegisterMutationVariables, TContext> => {

const mutationKey = getPostApiAccountRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountRegister>>, PostApiAccountRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountRegister>>>
    export type PostApiAccountRegisterMutationBody = NonReadonly<VoloAbpAccountRegisterDto> | undefined
    export type PostApiAccountRegisterMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountRegisterMutationVariables = {data?: NonReadonly<VoloAbpAccountRegisterDto>}

    export const usePostApiAccountRegister = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountRegister>>, TError,PostApiAccountRegisterMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountRegister>>,
        TError,
        PostApiAccountRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountRegisterMutationOptions(options), queryClient);
    }
    export const getPostApiAccountSendPasswordResetCodeUrl = () => {




  return `/api/account/send-password-reset-code`
}

export const postApiAccountSendPasswordResetCode = async (voloAbpAccountSendPasswordResetCodeDto?: VoloAbpAccountSendPasswordResetCodeDto, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<void>(getPostApiAccountSendPasswordResetCodeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountSendPasswordResetCodeDto)
  }
);}





export const getPostApiAccountSendPasswordResetCodeMutationKey = () => ['postApiAccountSendPasswordResetCode'] as const;

export const getPostApiAccountSendPasswordResetCodeMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>, TError,PostApiAccountSendPasswordResetCodeMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>, TError,PostApiAccountSendPasswordResetCodeMutationVariables, TContext> => {

const mutationKey = getPostApiAccountSendPasswordResetCodeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>, PostApiAccountSendPasswordResetCodeMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountSendPasswordResetCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountSendPasswordResetCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>>
    export type PostApiAccountSendPasswordResetCodeMutationBody = VoloAbpAccountSendPasswordResetCodeDto | undefined
    export type PostApiAccountSendPasswordResetCodeMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountSendPasswordResetCodeMutationVariables = {data?: VoloAbpAccountSendPasswordResetCodeDto}

    export const usePostApiAccountSendPasswordResetCode = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>, TError,PostApiAccountSendPasswordResetCodeMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountSendPasswordResetCode>>,
        TError,
        PostApiAccountSendPasswordResetCodeMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountSendPasswordResetCodeMutationOptions(options), queryClient);
    }
    export const getPostApiAccountVerifyPasswordResetTokenUrl = () => {




  return `/api/account/verify-password-reset-token`
}

export const postApiAccountVerifyPasswordResetToken = async (voloAbpAccountVerifyPasswordResetTokenInput?: VoloAbpAccountVerifyPasswordResetTokenInput, options?: Parameters<typeof abpMutator>[1]): Promise<boolean> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<boolean>(getPostApiAccountVerifyPasswordResetTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountVerifyPasswordResetTokenInput)
  }
);}





export const getPostApiAccountVerifyPasswordResetTokenMutationKey = () => ['postApiAccountVerifyPasswordResetToken'] as const;

export const getPostApiAccountVerifyPasswordResetTokenMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>, TError,PostApiAccountVerifyPasswordResetTokenMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>, TError,PostApiAccountVerifyPasswordResetTokenMutationVariables, TContext> => {

const mutationKey = getPostApiAccountVerifyPasswordResetTokenMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>, PostApiAccountVerifyPasswordResetTokenMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountVerifyPasswordResetToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountVerifyPasswordResetTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>>
    export type PostApiAccountVerifyPasswordResetTokenMutationBody = VoloAbpAccountVerifyPasswordResetTokenInput | undefined
    export type PostApiAccountVerifyPasswordResetTokenMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountVerifyPasswordResetTokenMutationVariables = {data?: VoloAbpAccountVerifyPasswordResetTokenInput}

    export const usePostApiAccountVerifyPasswordResetToken = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>, TError,PostApiAccountVerifyPasswordResetTokenMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountVerifyPasswordResetToken>>,
        TError,
        PostApiAccountVerifyPasswordResetTokenMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountVerifyPasswordResetTokenMutationOptions(options), queryClient);
    }
    export const getPostApiAccountResetPasswordUrl = () => {




  return `/api/account/reset-password`
}

export const postApiAccountResetPassword = async (voloAbpAccountResetPasswordDto?: VoloAbpAccountResetPasswordDto, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<void>(getPostApiAccountResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountResetPasswordDto)
  }
);}





export const getPostApiAccountResetPasswordMutationKey = () => ['postApiAccountResetPassword'] as const;

export const getPostApiAccountResetPasswordMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountResetPassword>>, TError,PostApiAccountResetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountResetPassword>>, TError,PostApiAccountResetPasswordMutationVariables, TContext> => {

const mutationKey = getPostApiAccountResetPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountResetPassword>>, PostApiAccountResetPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountResetPassword>>>
    export type PostApiAccountResetPasswordMutationBody = VoloAbpAccountResetPasswordDto | undefined
    export type PostApiAccountResetPasswordMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountResetPasswordMutationVariables = {data?: VoloAbpAccountResetPasswordDto}

    export const usePostApiAccountResetPassword = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountResetPassword>>, TError,PostApiAccountResetPasswordMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountResetPassword>>,
        TError,
        PostApiAccountResetPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountResetPasswordMutationOptions(options), queryClient);
    }
