/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult,
  VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getPostApiAccountLoginUrl = () => {


  

  return `/api/account/login`
}

export const postApiAccountLogin = async (voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo, options?: RequestInit): Promise<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult> => {
  
  return abpMutator<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult>(getPostApiAccountLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo,)
  }
);}




export const getPostApiAccountLoginMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext> => {

const mutationKey = ['postApiAccountLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountLogin>>, {data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountLogin>>>
    export type PostApiAccountLoginMutationBody = VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo
    export type PostApiAccountLoginMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiAccountLogin = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountLogin>>,
        TError,
        {data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo},
        TContext
      > => {

      const mutationOptions = getPostApiAccountLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getGetApiAccountLogoutUrl = () => {


  

  return `/api/account/logout`
}

export const getApiAccountLogout = async ( options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getGetApiAccountLogoutUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAccountLogoutQueryKey = () => {
    return [
    `/api/account/logout`
    ] as const;
    }

    
export const getGetApiAccountLogoutQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountLogoutQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountLogout>>> = ({ signal }) => getApiAccountLogout({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiAccountLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountLogout>>>
export type GetApiAccountLogoutQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiAccountLogoutQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiAccountCheckPasswordUrl = () => {


  

  return `/api/account/check-password`
}

export const postApiAccountCheckPassword = async (voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo, options?: RequestInit): Promise<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult> => {
  
  return abpMutator<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult>(getPostApiAccountCheckPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo,)
  }
);}




export const getPostApiAccountCheckPasswordMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext> => {

const mutationKey = ['postApiAccountCheckPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, {data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountCheckPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountCheckPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountCheckPassword>>>
    export type PostApiAccountCheckPasswordMutationBody = VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo
    export type PostApiAccountCheckPasswordMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiAccountCheckPassword = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,{data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountCheckPassword>>,
        TError,
        {data: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo},
        TContext
      > => {

      const mutationOptions = getPostApiAccountCheckPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    