/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult,
  VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostApiAccountLoginUrl = () => {




  return `/api/account/login`
}

export const postApiAccountLogin = async (voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo?: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult>(getPostApiAccountLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo)
  }
);}





export const getPostApiAccountLoginMutationKey = () => ['postApiAccountLogin'] as const;

export const getPostApiAccountLoginMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,PostApiAccountLoginMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,PostApiAccountLoginMutationVariables, TContext> => {

const mutationKey = getPostApiAccountLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountLogin>>, PostApiAccountLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountLogin>>>
    export type PostApiAccountLoginMutationBody = VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo | undefined
    export type PostApiAccountLoginMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountLoginMutationVariables = {data?: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}

    export const usePostApiAccountLogin = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountLogin>>, TError,PostApiAccountLoginMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountLogin>>,
        TError,
        PostApiAccountLoginMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountLoginMutationOptions(options), queryClient);
    }
    export const getGetApiAccountLogoutUrl = () => {




  return `/api/account/logout`
}

export const getApiAccountLogout = async ( options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

  return abpMutator<void>(getGetApiAccountLogoutUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAccountLogoutQueryKey = () => {
    return [
    `/api/account/logout`
    ] as const;
    }


export const getGetApiAccountLogoutQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountLogoutQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountLogout>>> = ({ signal }) => getApiAccountLogout({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountLogoutQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountLogout>>>
export type GetApiAccountLogoutQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountLogout>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountLogout>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountLogout<TData = Awaited<ReturnType<typeof getApiAccountLogout>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountLogout>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountLogoutQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostApiAccountCheckPasswordUrl = () => {




  return `/api/account/check-password`
}

export const postApiAccountCheckPassword = async (voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo?: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult>(getPostApiAccountCheckPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpAccountWebAreasAccountControllersModelsUserLoginInfo)
  }
);}





export const getPostApiAccountCheckPasswordMutationKey = () => ['postApiAccountCheckPassword'] as const;

export const getPostApiAccountCheckPasswordMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,PostApiAccountCheckPasswordMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,PostApiAccountCheckPasswordMutationVariables, TContext> => {

const mutationKey = getPostApiAccountCheckPasswordMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, PostApiAccountCheckPasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountCheckPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountCheckPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountCheckPassword>>>
    export type PostApiAccountCheckPasswordMutationBody = VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo | undefined
    export type PostApiAccountCheckPasswordMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiAccountCheckPasswordMutationVariables = {data?: VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo}

    export const usePostApiAccountCheckPassword = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountCheckPassword>>, TError,PostApiAccountCheckPasswordMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountCheckPassword>>,
        TError,
        PostApiAccountCheckPasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiAccountCheckPasswordMutationOptions(options), queryClient);
    }
