/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiFeatureManagementFeaturesParams,
  GetApiFeatureManagementFeaturesParams,
  PutApiFeatureManagementFeaturesParams,
  VoloAbpFeatureManagementGetFeatureListResultDto,
  VoloAbpFeatureManagementUpdateFeaturesDto,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiFeatureManagementFeaturesUrl = (params?: GetApiFeatureManagementFeaturesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/feature-management/features?${stringifiedParams}` : `/api/feature-management/features`
}

export const getApiFeatureManagementFeatures = async (params?: GetApiFeatureManagementFeaturesParams, options?: RequestInit): Promise<VoloAbpFeatureManagementGetFeatureListResultDto> => {
  
  return abpMutator<VoloAbpFeatureManagementGetFeatureListResultDto>(getGetApiFeatureManagementFeaturesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiFeatureManagementFeaturesQueryKey = (params?: GetApiFeatureManagementFeaturesParams,) => {
    return [
    `/api/feature-management/features`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiFeatureManagementFeaturesQueryOptions = <TData = Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiFeatureManagementFeaturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiFeatureManagementFeaturesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>> = ({ signal }) => getApiFeatureManagementFeatures(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiFeatureManagementFeaturesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>>
export type GetApiFeatureManagementFeaturesQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiFeatureManagementFeatures<TData = Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiFeatureManagementFeaturesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiFeatureManagementFeatures<TData = Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiFeatureManagementFeaturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>,
          TError,
          Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiFeatureManagementFeatures<TData = Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiFeatureManagementFeaturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiFeatureManagementFeatures<TData = Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiFeatureManagementFeaturesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiFeatureManagementFeatures>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiFeatureManagementFeaturesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiFeatureManagementFeaturesUrl = (params?: PutApiFeatureManagementFeaturesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/feature-management/features?${stringifiedParams}` : `/api/feature-management/features`
}

export const putApiFeatureManagementFeatures = async (voloAbpFeatureManagementUpdateFeaturesDto: VoloAbpFeatureManagementUpdateFeaturesDto,
    params?: PutApiFeatureManagementFeaturesParams, options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getPutApiFeatureManagementFeaturesUrl(params),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpFeatureManagementUpdateFeaturesDto,)
  }
);}




export const getPutApiFeatureManagementFeaturesMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>, TError,{data: VoloAbpFeatureManagementUpdateFeaturesDto;params?: PutApiFeatureManagementFeaturesParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>, TError,{data: VoloAbpFeatureManagementUpdateFeaturesDto;params?: PutApiFeatureManagementFeaturesParams}, TContext> => {

const mutationKey = ['putApiFeatureManagementFeatures'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>, {data: VoloAbpFeatureManagementUpdateFeaturesDto;params?: PutApiFeatureManagementFeaturesParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putApiFeatureManagementFeatures(data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiFeatureManagementFeaturesMutationResult = NonNullable<Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>>
    export type PutApiFeatureManagementFeaturesMutationBody = VoloAbpFeatureManagementUpdateFeaturesDto
    export type PutApiFeatureManagementFeaturesMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePutApiFeatureManagementFeatures = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>, TError,{data: VoloAbpFeatureManagementUpdateFeaturesDto;params?: PutApiFeatureManagementFeaturesParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiFeatureManagementFeatures>>,
        TError,
        {data: VoloAbpFeatureManagementUpdateFeaturesDto;params?: PutApiFeatureManagementFeaturesParams},
        TContext
      > => {

      const mutationOptions = getPutApiFeatureManagementFeaturesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getDeleteApiFeatureManagementFeaturesUrl = (params?: DeleteApiFeatureManagementFeaturesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/feature-management/features?${stringifiedParams}` : `/api/feature-management/features`
}

export const deleteApiFeatureManagementFeatures = async (params?: DeleteApiFeatureManagementFeaturesParams, options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getDeleteApiFeatureManagementFeaturesUrl(params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteApiFeatureManagementFeaturesMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>, TError,{params?: DeleteApiFeatureManagementFeaturesParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>, TError,{params?: DeleteApiFeatureManagementFeaturesParams}, TContext> => {

const mutationKey = ['deleteApiFeatureManagementFeatures'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>, {params?: DeleteApiFeatureManagementFeaturesParams}> = (props) => {
          const {params} = props ?? {};

          return  deleteApiFeatureManagementFeatures(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiFeatureManagementFeaturesMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>>
    
    export type DeleteApiFeatureManagementFeaturesMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const useDeleteApiFeatureManagementFeatures = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>, TError,{params?: DeleteApiFeatureManagementFeaturesParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiFeatureManagementFeatures>>,
        TError,
        {params?: DeleteApiFeatureManagementFeaturesParams},
        TContext
      > => {

      const mutationOptions = getDeleteApiFeatureManagementFeaturesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    