/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiIdentityUsersParams,
  ListResultDtoOfIdentityRoleDto,
  PagedResultDtoOfIdentityUserDto,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpIdentityIdentityUserCreateDto,
  VoloAbpIdentityIdentityUserDto,
  VoloAbpIdentityIdentityUserUpdateDto,
  VoloAbpIdentityIdentityUserUpdateRolesDto
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetApiIdentityUsersIdUrl = (id: string,) => {




  return `/api/identity/users/${id}`
}

export const getApiIdentityUsersId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

  return abpMutator<VoloAbpIdentityIdentityUserDto>(getGetApiIdentityUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersIdQueryKey = (id: string,) => {
    return [
    `/api/identity/users/${id}`
    ] as const;
    }


export const getGetApiIdentityUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersId>>> = ({ signal }) => getApiIdentityUsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersId>>>
export type GetApiIdentityUsersIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersId<TData = Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersId<TData = Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersId<TData = Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersId<TData = Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutApiIdentityUsersIdUrl = (id: string,) => {




  return `/api/identity/users/${id}`
}

export const putApiIdentityUsersId = async (id: string,
    voloAbpIdentityIdentityUserUpdateDto?: NonReadonly<VoloAbpIdentityIdentityUserUpdateDto>, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpIdentityIdentityUserDto>(getPutApiIdentityUsersIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpIdentityIdentityUserUpdateDto)
  }
);}





export const getPutApiIdentityUsersIdMutationKey = () => ['putApiIdentityUsersId'] as const;

export const getPutApiIdentityUsersIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersId>>, TError,PutApiIdentityUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersId>>, TError,PutApiIdentityUsersIdMutationVariables, TContext> => {

const mutationKey = getPutApiIdentityUsersIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiIdentityUsersId>>, PutApiIdentityUsersIdMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiIdentityUsersId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiIdentityUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiIdentityUsersId>>>
    export type PutApiIdentityUsersIdMutationBody = NonReadonly<VoloAbpIdentityIdentityUserUpdateDto> | undefined
    export type PutApiIdentityUsersIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PutApiIdentityUsersIdMutationVariables = {id: string;data?: NonReadonly<VoloAbpIdentityIdentityUserUpdateDto>}

    export const usePutApiIdentityUsersId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersId>>, TError,PutApiIdentityUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiIdentityUsersId>>,
        TError,
        PutApiIdentityUsersIdMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiIdentityUsersIdMutationOptions(options), queryClient);
    }
    export const getDeleteApiIdentityUsersIdUrl = (id: string,) => {




  return `/api/identity/users/${id}`
}

export const deleteApiIdentityUsersId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

  return abpMutator<void>(getDeleteApiIdentityUsersIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteApiIdentityUsersIdMutationKey = () => ['deleteApiIdentityUsersId'] as const;

export const getDeleteApiIdentityUsersIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityUsersId>>, TError,DeleteApiIdentityUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityUsersId>>, TError,DeleteApiIdentityUsersIdMutationVariables, TContext> => {

const mutationKey = getDeleteApiIdentityUsersIdMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiIdentityUsersId>>, DeleteApiIdentityUsersIdMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  deleteApiIdentityUsersId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiIdentityUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiIdentityUsersId>>>

    export type DeleteApiIdentityUsersIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type DeleteApiIdentityUsersIdMutationVariables = {id: string}

    export const useDeleteApiIdentityUsersId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityUsersId>>, TError,DeleteApiIdentityUsersIdMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiIdentityUsersId>>,
        TError,
        DeleteApiIdentityUsersIdMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteApiIdentityUsersIdMutationOptions(options), queryClient);
    }
    export const getGetApiIdentityUsersUrl = (params?: GetApiIdentityUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/identity/users?${stringifiedParams}` : `/api/identity/users`
}

export const getApiIdentityUsers = async (params?: GetApiIdentityUsersParams, options?: Parameters<typeof abpMutator>[1]): Promise<PagedResultDtoOfIdentityUserDto> => {

  return abpMutator<PagedResultDtoOfIdentityUserDto>(getGetApiIdentityUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersQueryKey = (params?: GetApiIdentityUsersParams,) => {
    return [
    `/api/identity/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiIdentityUsersQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsers>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiIdentityUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsers>>> = ({ signal }) => getApiIdentityUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsers>>>
export type GetApiIdentityUsersQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsers<TData = Awaited<ReturnType<typeof getApiIdentityUsers>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiIdentityUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsers<TData = Awaited<ReturnType<typeof getApiIdentityUsers>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsers>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsers<TData = Awaited<ReturnType<typeof getApiIdentityUsers>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsers<TData = Awaited<ReturnType<typeof getApiIdentityUsers>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsers>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostApiIdentityUsersUrl = () => {




  return `/api/identity/users`
}

export const postApiIdentityUsers = async (voloAbpIdentityIdentityUserCreateDto?: NonReadonly<VoloAbpIdentityIdentityUserCreateDto>, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<VoloAbpIdentityIdentityUserDto>(getPostApiIdentityUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpIdentityIdentityUserCreateDto)
  }
);}





export const getPostApiIdentityUsersMutationKey = () => ['postApiIdentityUsers'] as const;

export const getPostApiIdentityUsersMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityUsers>>, TError,PostApiIdentityUsersMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityUsers>>, TError,PostApiIdentityUsersMutationVariables, TContext> => {

const mutationKey = getPostApiIdentityUsersMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiIdentityUsers>>, PostApiIdentityUsersMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiIdentityUsers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiIdentityUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postApiIdentityUsers>>>
    export type PostApiIdentityUsersMutationBody = NonReadonly<VoloAbpIdentityIdentityUserCreateDto> | undefined
    export type PostApiIdentityUsersMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiIdentityUsersMutationVariables = {data?: NonReadonly<VoloAbpIdentityIdentityUserCreateDto>}

    export const usePostApiIdentityUsers = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityUsers>>, TError,PostApiIdentityUsersMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiIdentityUsers>>,
        TError,
        PostApiIdentityUsersMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiIdentityUsersMutationOptions(options), queryClient);
    }
    export const getGetApiIdentityUsersByIdIdUrl = (id: string,) => {




  return `/api/identity/users/by-id/${id}`
}

export const getApiIdentityUsersByIdId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

  return abpMutator<VoloAbpIdentityIdentityUserDto>(getGetApiIdentityUsersByIdIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersByIdIdQueryKey = (id: string,) => {
    return [
    `/api/identity/users/by-id/${id}`
    ] as const;
    }


export const getGetApiIdentityUsersByIdIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersByIdIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>> = ({ signal }) => getApiIdentityUsersByIdId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersByIdIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>>
export type GetApiIdentityUsersByIdIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersByIdId<TData = Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByIdId<TData = Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByIdId<TData = Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersByIdId<TData = Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersByIdIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetApiIdentityUsersIdRolesUrl = (id: string,) => {




  return `/api/identity/users/${id}/roles`
}

export const getApiIdentityUsersIdRoles = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<ListResultDtoOfIdentityRoleDto> => {

  return abpMutator<ListResultDtoOfIdentityRoleDto>(getGetApiIdentityUsersIdRolesUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersIdRolesQueryKey = (id: string,) => {
    return [
    `/api/identity/users/${id}/roles`
    ] as const;
    }


export const getGetApiIdentityUsersIdRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersIdRolesQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>> = ({ signal }) => getApiIdentityUsersIdRoles(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersIdRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>>
export type GetApiIdentityUsersIdRolesQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersIdRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersIdRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersIdRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersIdRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersIdRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersIdRolesQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPutApiIdentityUsersIdRolesUrl = (id: string,) => {




  return `/api/identity/users/${id}/roles`
}

export const putApiIdentityUsersIdRoles = async (id: string,
    voloAbpIdentityIdentityUserUpdateRolesDto?: VoloAbpIdentityIdentityUserUpdateRolesDto, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<void>(getPutApiIdentityUsersIdRolesUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpIdentityIdentityUserUpdateRolesDto)
  }
);}





export const getPutApiIdentityUsersIdRolesMutationKey = () => ['putApiIdentityUsersIdRoles'] as const;

export const getPutApiIdentityUsersIdRolesMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>, TError,PutApiIdentityUsersIdRolesMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>, TError,PutApiIdentityUsersIdRolesMutationVariables, TContext> => {

const mutationKey = getPutApiIdentityUsersIdRolesMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>, PutApiIdentityUsersIdRolesMutationVariables> = (props) => {
          const {id,data} = props ?? {};

          return  putApiIdentityUsersIdRoles(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiIdentityUsersIdRolesMutationResult = NonNullable<Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>>
    export type PutApiIdentityUsersIdRolesMutationBody = VoloAbpIdentityIdentityUserUpdateRolesDto | undefined
    export type PutApiIdentityUsersIdRolesMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PutApiIdentityUsersIdRolesMutationVariables = {id: string;data?: VoloAbpIdentityIdentityUserUpdateRolesDto}

    export const usePutApiIdentityUsersIdRoles = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>, TError,PutApiIdentityUsersIdRolesMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiIdentityUsersIdRoles>>,
        TError,
        PutApiIdentityUsersIdRolesMutationVariables,
        TContext
      > => {
      return useMutation(getPutApiIdentityUsersIdRolesMutationOptions(options), queryClient);
    }
    export const getGetApiIdentityUsersAssignableRolesUrl = () => {




  return `/api/identity/users/assignable-roles`
}

export const getApiIdentityUsersAssignableRoles = async ( options?: Parameters<typeof abpMutator>[1]): Promise<ListResultDtoOfIdentityRoleDto> => {

  return abpMutator<ListResultDtoOfIdentityRoleDto>(getGetApiIdentityUsersAssignableRolesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersAssignableRolesQueryKey = () => {
    return [
    `/api/identity/users/assignable-roles`
    ] as const;
    }


export const getGetApiIdentityUsersAssignableRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersAssignableRolesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>> = ({ signal }) => getApiIdentityUsersAssignableRoles({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersAssignableRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>>
export type GetApiIdentityUsersAssignableRolesQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersAssignableRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersAssignableRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersAssignableRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersAssignableRoles<TData = Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersAssignableRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersAssignableRolesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetApiIdentityUsersByUsernameUserNameUrl = (userName: string,) => {




  return `/api/identity/users/by-username/${userName}`
}

export const getApiIdentityUsersByUsernameUserName = async (userName: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

  return abpMutator<VoloAbpIdentityIdentityUserDto>(getGetApiIdentityUsersByUsernameUserNameUrl(userName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersByUsernameUserNameQueryKey = (userName: string,) => {
    return [
    `/api/identity/users/by-username/${userName}`
    ] as const;
    }


export const getGetApiIdentityUsersByUsernameUserNameQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersByUsernameUserNameQueryKey(userName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>> = ({ signal }) => getApiIdentityUsersByUsernameUserName(userName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: userName !== null && userName !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersByUsernameUserNameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>>
export type GetApiIdentityUsersByUsernameUserNameQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersByUsernameUserNameQueryOptions(userName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetApiIdentityUsersByEmailEmailUrl = (email: string,) => {




  return `/api/identity/users/by-email/${email}`
}

export const getApiIdentityUsersByEmailEmail = async (email: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpIdentityIdentityUserDto> => {

  return abpMutator<VoloAbpIdentityIdentityUserDto>(getGetApiIdentityUsersByEmailEmailUrl(email),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiIdentityUsersByEmailEmailQueryKey = (email: string,) => {
    return [
    `/api/identity/users/by-email/${email}`
    ] as const;
    }


export const getGetApiIdentityUsersByEmailEmailQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersByEmailEmailQueryKey(email);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>> = ({ signal }) => getApiIdentityUsersByEmailEmail(email, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: email !== null && email !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiIdentityUsersByEmailEmailQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>>
export type GetApiIdentityUsersByEmailEmailQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersByEmailEmail<TData = Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 email: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByEmailEmail<TData = Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiIdentityUsersByEmailEmail<TData = Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiIdentityUsersByEmailEmail<TData = Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 email: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersByEmailEmail>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiIdentityUsersByEmailEmailQueryOptions(email,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






