/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAbpApiDefinitionQueryParams = zod.object({
  "IncludeTypes": zod.boolean().optional(),
  "IncludeDescriptions": zod.boolean().optional()
})

export const getApiAbpApiDefinitionResponse = zod.object({
  "modules": zod.record(zod.string(), zod.object({
  "rootPath": zod.string().nullish(),
  "remoteServiceName": zod.string().nullish(),
  "controllers": zod.record(zod.string(), zod.object({
  "controllerName": zod.string().nullish(),
  "controllerGroupName": zod.string().nullish(),
  "isRemoteService": zod.boolean().optional(),
  "isIntegrationService": zod.boolean().optional(),
  "apiVersion": zod.string().nullish(),
  "type": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "remarks": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "interfaces": zod.array(zod.object({
  "type": zod.string().nullish(),
  "name": zod.string().nullish(),
  "methods": zod.array(zod.object({
  "name": zod.string().nullish(),
  "parametersOnMethod": zod.array(zod.object({
  "name": zod.string().nullish(),
  "typeAsString": zod.string().nullish(),
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "isOptional": zod.boolean().optional(),
  "defaultValue": zod.unknown().nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish(),
  "returnValue": zod.object({
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "summary": zod.string().nullish()
}).optional()
})).nullish()
})).nullish(),
  "actions": zod.record(zod.string(), zod.object({
  "uniqueName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "httpMethod": zod.string().nullish(),
  "url": zod.string().nullish(),
  "supportedVersions": zod.array(zod.string()).nullish(),
  "parametersOnMethod": zod.array(zod.object({
  "name": zod.string().nullish(),
  "typeAsString": zod.string().nullish(),
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "isOptional": zod.boolean().optional(),
  "defaultValue": zod.unknown().nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish(),
  "parameters": zod.array(zod.object({
  "nameOnMethod": zod.string().nullish(),
  "name": zod.string().nullish(),
  "jsonName": zod.string().nullish(),
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "isOptional": zod.boolean().optional(),
  "defaultValue": zod.unknown().nullish(),
  "constraintTypes": zod.array(zod.string()).nullish(),
  "bindingSourceId": zod.string().nullish(),
  "descriptorName": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish(),
  "returnValue": zod.object({
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "summary": zod.string().nullish()
}).optional(),
  "allowAnonymous": zod.boolean().nullish(),
  "authorizeDatas": zod.array(zod.object({
  "policy": zod.string().nullish(),
  "roles": zod.string().nullish()
})).nullish(),
  "implementFrom": zod.string().nullish(),
  "summary": zod.string().nullish(),
  "remarks": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish()
})).nullish()
})).nullish(),
  "types": zod.record(zod.string(), zod.object({
  "baseType": zod.string().nullish(),
  "isEnum": zod.boolean().optional(),
  "enumNames": zod.array(zod.string()).nullish(),
  "enumValues": zod.array(zod.unknown()).nullish(),
  "genericArguments": zod.array(zod.string()).nullish(),
  "properties": zod.array(zod.object({
  "name": zod.string().nullish(),
  "jsonName": zod.string().nullish(),
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "isRequired": zod.boolean().optional(),
  "minLength": zod.number().nullish(),
  "maxLength": zod.number().nullish(),
  "minimum": zod.string().nullish(),
  "maximum": zod.string().nullish(),
  "regex": zod.string().nullish(),
  "isNullable": zod.boolean().optional(),
  "summary": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish(),
  "summary": zod.string().nullish(),
  "remarks": zod.string().nullish(),
  "description": zod.string().nullish(),
  "displayName": zod.string().nullish()
})).nullish()
})

