/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

export const getApiFeatureManagementFeaturesResponse = zod.object({
  "groups": zod.array(zod.object({
  "name": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "features": zod.array(zod.object({
  "name": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "value": zod.string().nullish(),
  "provider": zod.object({
  "name": zod.string().nullish(),
  "key": zod.string().nullish()
}).optional(),
  "description": zod.string().nullish(),
  "valueType": zod.object({
  "name": zod.string().nullish(),
  "properties": zod.record(zod.string(), zod.unknown().nullable()).nullish(),
  "validator": zod.object({
  "name": zod.string().nullish(),
  "properties": zod.record(zod.string(), zod.unknown().nullable()).nullish()
}).optional()
}).optional(),
  "depth": zod.number().optional(),
  "parentName": zod.string().nullish()
})).nullish()
})).nullish()
})

export const putApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

export const putApiFeatureManagementFeaturesBody = zod.object({
  "features": zod.array(zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
})).nullish()
})

export const deleteApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

