/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

export const GetApiFeatureManagementFeaturesResponse = zod.object({
  "groups": zod.array(zod.object({
  "name": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "features": zod.array(zod.object({
  "name": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "value": zod.string().nullish(),
  "provider": zod.object({
  "name": zod.string().nullish(),
  "key": zod.string().nullish()
}).optional(),
  "description": zod.string().nullish(),
  "valueType": zod.object({
  "name": zod.string().nullish(),
  "properties": zod.record(zod.string(), zod.unknown()).nullish(),
  "validator": zod.object({
  "name": zod.string().nullish(),
  "properties": zod.record(zod.string(), zod.unknown()).nullish()
}).optional()
}).optional(),
  "depth": zod.int().optional(),
  "parentName": zod.string().nullish()
})).nullish()
})).nullish()
})

export const PutApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

export const PutApiFeatureManagementFeaturesBody = zod.object({
  "features": zod.array(zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
})).nullish()
})

export const PutApiFeatureManagementFeaturesResponse = zod.unknown()

export const DeleteApiFeatureManagementFeaturesQueryParams = zod.object({
  "providerName": zod.string().optional(),
  "providerKey": zod.string().optional()
})

export const DeleteApiFeatureManagementFeaturesResponse = zod.unknown()

