/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const postApiAccountLoginBodyUserNameOrEmailAddressMin = 0;
export const postApiAccountLoginBodyUserNameOrEmailAddressMax = 255;

export const postApiAccountLoginBodyPasswordMin = 0;
export const postApiAccountLoginBodyPasswordMax = 32;



export const postApiAccountLoginBody = zod.object({
  "userNameOrEmailAddress": zod.string().min(postApiAccountLoginBodyUserNameOrEmailAddressMin).max(postApiAccountLoginBodyUserNameOrEmailAddressMax),
  "password": zod.string().min(postApiAccountLoginBodyPasswordMin).max(postApiAccountLoginBodyPasswordMax),
  "rememberMe": zod.boolean().optional()
})

export const postApiAccountLoginResponse = zod.object({
  "result": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).optional(),
  "description": zod.string().nullish()
})

export const postApiAccountCheckPasswordBodyUserNameOrEmailAddressMin = 0;
export const postApiAccountCheckPasswordBodyUserNameOrEmailAddressMax = 255;

export const postApiAccountCheckPasswordBodyPasswordMin = 0;
export const postApiAccountCheckPasswordBodyPasswordMax = 32;



export const postApiAccountCheckPasswordBody = zod.object({
  "userNameOrEmailAddress": zod.string().min(postApiAccountCheckPasswordBodyUserNameOrEmailAddressMin).max(postApiAccountCheckPasswordBodyUserNameOrEmailAddressMax),
  "password": zod.string().min(postApiAccountCheckPasswordBodyPasswordMin).max(postApiAccountCheckPasswordBodyPasswordMax),
  "rememberMe": zod.boolean().optional()
})

export const postApiAccountCheckPasswordResponse = zod.object({
  "result": zod.union([zod.literal(1),zod.literal(2),zod.literal(3),zod.literal(4),zod.literal(5)]).optional(),
  "description": zod.string().nullish()
})

