/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VoloAbpAccountChangePasswordInput,
  VoloAbpAccountProfileDto,
  VoloAbpAccountUpdateProfileDto,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiAccountMyProfileUrl = () => {


  

  return `/api/account/my-profile`
}

export const getApiAccountMyProfile = async ( options?: RequestInit): Promise<VoloAbpAccountProfileDto> => {
  
  return abpMutator<VoloAbpAccountProfileDto>(getGetApiAccountMyProfileUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAccountMyProfileQueryKey = () => {
    return [
    `/api/account/my-profile`
    ] as const;
    }

    
export const getGetApiAccountMyProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountMyProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountMyProfile>>> = ({ signal }) => getApiAccountMyProfile({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiAccountMyProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountMyProfile>>>
export type GetApiAccountMyProfileQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAccountMyProfile<TData = Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountMyProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountMyProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAccountMyProfile<TData = Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountMyProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountMyProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAccountMyProfile<TData = Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiAccountMyProfile<TData = Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountMyProfile>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiAccountMyProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiAccountMyProfileUrl = () => {


  

  return `/api/account/my-profile`
}

export const putApiAccountMyProfile = async (voloAbpAccountUpdateProfileDto: NonReadonly<VoloAbpAccountUpdateProfileDto>, options?: RequestInit): Promise<VoloAbpAccountProfileDto> => {
  
  return abpMutator<VoloAbpAccountProfileDto>(getPutApiAccountMyProfileUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpAccountUpdateProfileDto,)
  }
);}




export const getPutApiAccountMyProfileMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountMyProfile>>, TError,{data: NonReadonly<VoloAbpAccountUpdateProfileDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiAccountMyProfile>>, TError,{data: NonReadonly<VoloAbpAccountUpdateProfileDto>}, TContext> => {

const mutationKey = ['putApiAccountMyProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAccountMyProfile>>, {data: NonReadonly<VoloAbpAccountUpdateProfileDto>}> = (props) => {
          const {data} = props ?? {};

          return  putApiAccountMyProfile(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAccountMyProfileMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAccountMyProfile>>>
    export type PutApiAccountMyProfileMutationBody = NonReadonly<VoloAbpAccountUpdateProfileDto>
    export type PutApiAccountMyProfileMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePutApiAccountMyProfile = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountMyProfile>>, TError,{data: NonReadonly<VoloAbpAccountUpdateProfileDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAccountMyProfile>>,
        TError,
        {data: NonReadonly<VoloAbpAccountUpdateProfileDto>},
        TContext
      > => {

      const mutationOptions = getPutApiAccountMyProfileMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getPostApiAccountMyProfileChangePasswordUrl = () => {


  

  return `/api/account/my-profile/change-password`
}

export const postApiAccountMyProfileChangePassword = async (voloAbpAccountChangePasswordInput: VoloAbpAccountChangePasswordInput, options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getPostApiAccountMyProfileChangePasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpAccountChangePasswordInput,)
  }
);}




export const getPostApiAccountMyProfileChangePasswordMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>, TError,{data: VoloAbpAccountChangePasswordInput}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>, TError,{data: VoloAbpAccountChangePasswordInput}, TContext> => {

const mutationKey = ['postApiAccountMyProfileChangePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>, {data: VoloAbpAccountChangePasswordInput}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountMyProfileChangePassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountMyProfileChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>>
    export type PostApiAccountMyProfileChangePasswordMutationBody = VoloAbpAccountChangePasswordInput
    export type PostApiAccountMyProfileChangePasswordMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiAccountMyProfileChangePassword = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>, TError,{data: VoloAbpAccountChangePasswordInput}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountMyProfileChangePassword>>,
        TError,
        {data: VoloAbpAccountChangePasswordInput},
        TContext
      > => {

      const mutationOptions = getPostApiAccountMyProfileChangePasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    