/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type DeleteApiPermissionManagementPermissionsResourceParams = {
resourceName?: string;
resourceKey?: string;
providerName?: string;
providerKey?: string;
};
