/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type GetApiPermissionManagementPermissionsByGroupParams = {
groupName?: string;
providerName?: string;
providerKey?: string;
};
