/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type GetApiPermissionManagementPermissionsSearchResourceProviderKeysParams = {
resourceName?: string;
serviceName?: string;
filter?: string;
page?: number;
};
