/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type GetApiPermissionManagementPermissionsResourceByProviderParams = {
resourceName?: string;
resourceKey?: string;
providerName?: string;
providerKey?: string;
};
