/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type GetApiIdentityUsersLookupSearchParams = {
Filter?: string;
Sorting?: string;
/**
 * @minimum 0
 * @maximum 2147483647
 */
SkipCount?: number;
/**
 * @minimum 1
 * @maximum 2147483647
 */
MaxResultCount?: number;
ExtraProperties?: {[key: string]: unknown};
};
