/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpUsersUserData } from './voloAbpUsersUserData';

export interface ListResultDtoOfUserData {
  /** @nullable */
  items?: VoloAbpUsersUserData[] | null;
}
