/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityRoleDto } from './voloAbpIdentityIdentityRoleDto';

export interface PagedResultDtoOfIdentityRoleDto {
  /** @nullable */
  items?: VoloAbpIdentityIdentityRoleDto[] | null;
  totalCount?: number;
}
