/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserDto } from './voloAbpIdentityIdentityUserDto';

export interface PagedResultDtoOfIdentityUserDto {
  /** @nullable */
  items?: VoloAbpIdentityIdentityUserDto[] | null;
  totalCount?: number;
}
