/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantDto } from './voloAbpTenantManagementTenantDto';

export interface PagedResultDtoOfTenantDto {
  /** @nullable */
  items?: VoloAbpTenantManagementTenantDto[] | null;
  totalCount?: number;
}
