/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type PutApiMultiTenancyTenantsIdDefaultConnectionStringParams = {
defaultConnectionString?: string;
};
