/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementPermissionGroupDto } from './voloAbpPermissionManagementPermissionGroupDto';

export interface VoloAbpPermissionManagementGetPermissionListResultDto {
  /** @nullable */
  entityDisplayName?: string | null;
  /** @nullable */
  groups?: VoloAbpPermissionManagementPermissionGroupDto[] | null;
}
