/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingModuleApiDescriptionModel } from './voloAbpHttpModelingModuleApiDescriptionModel';

/**
 * @nullable
 */
export type VoloAbpHttpModelingApplicationApiDescriptionModelModules = {[key: string]: VoloAbpHttpModelingModuleApiDescriptionModel} | null;
