/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingActionApiDescriptionModel } from './voloAbpHttpModelingActionApiDescriptionModel';

/**
 * @nullable
 */
export type VoloAbpHttpModelingControllerApiDescriptionModelActions = {[key: string]: VoloAbpHttpModelingActionApiDescriptionModel} | null;
