/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserDtoExtraProperties } from './voloAbpIdentityIdentityUserDtoExtraProperties';

export interface VoloAbpIdentityIdentityUserDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpIdentityIdentityUserDtoExtraProperties;
  id?: string;
  creationTime?: string;
  /** @nullable */
  creatorId?: string | null;
  /** @nullable */
  lastModificationTime?: string | null;
  /** @nullable */
  lastModifierId?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  deleterId?: string | null;
  /** @nullable */
  deletionTime?: string | null;
  /** @nullable */
  tenantId?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  email?: string | null;
  emailConfirmed?: boolean;
  /** @nullable */
  phoneNumber?: string | null;
  phoneNumberConfirmed?: boolean;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  accessFailedCount?: number;
  /** @nullable */
  lockoutEnd?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
  entityVersion?: number;
  /** @nullable */
  lastPasswordChangeTime?: string | null;
}
