/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAccountSendPasswordResetCodeDto {
  /**
   * @minLength 0
   * @maxLength 256
   */
  email: string;
  /** @minLength 1 */
  appName: string;
  /** @nullable */
  returnUrl?: string | null;
  /** @nullable */
  returnUrlHash?: string | null;
}
