/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpHttpRemoteServiceValidationErrorInfo {
  /** @nullable */
  message?: string | null;
  /** @nullable */
  members?: string[] | null;
}
