/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModel } from './voloAbpHttpModelingMethodParameterApiDescriptionModel';
import type { VoloAbpHttpModelingParameterApiDescriptionModel } from './voloAbpHttpModelingParameterApiDescriptionModel';
import type { VoloAbpHttpModelingReturnValueApiDescriptionModel } from './voloAbpHttpModelingReturnValueApiDescriptionModel';
import type { VoloAbpHttpModelingAuthorizeDataApiDescriptionModel } from './voloAbpHttpModelingAuthorizeDataApiDescriptionModel';

export interface VoloAbpHttpModelingActionApiDescriptionModel {
  /** @nullable */
  uniqueName?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  httpMethod?: string | null;
  /** @nullable */
  url?: string | null;
  /** @nullable */
  supportedVersions?: string[] | null;
  /** @nullable */
  parametersOnMethod?: VoloAbpHttpModelingMethodParameterApiDescriptionModel[] | null;
  /** @nullable */
  parameters?: VoloAbpHttpModelingParameterApiDescriptionModel[] | null;
  returnValue?: VoloAbpHttpModelingReturnValueApiDescriptionModel;
  /** @nullable */
  allowAnonymous?: boolean | null;
  /** @nullable */
  authorizeDatas?: VoloAbpHttpModelingAuthorizeDataApiDescriptionModel[] | null;
  /** @nullable */
  implementFrom?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  remarks?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  displayName?: string | null;
}
