/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementGrantedResourcePermissionDto } from './voloAbpPermissionManagementGrantedResourcePermissionDto';

export interface VoloAbpPermissionManagementResourcePermissionGrantInfoDto {
  /** @nullable */
  providerName?: string | null;
  /** @nullable */
  providerKey?: string | null;
  /** @nullable */
  providerDisplayName?: string | null;
  /** @nullable */
  providerNameDisplayName?: string | null;
  /** @nullable */
  permissions?: VoloAbpPermissionManagementGrantedResourcePermissionDto[] | null;
}
