/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementProviderInfoDto } from './voloAbpPermissionManagementProviderInfoDto';

export interface VoloAbpPermissionManagementPermissionGrantInfoDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  parentName?: string | null;
  isGranted?: boolean;
  /** @nullable */
  allowedProviders?: string[] | null;
  /** @nullable */
  grantedProviders?: VoloAbpPermissionManagementProviderInfoDto[] | null;
  isEditable?: boolean;
}
