/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingApplicationApiDescriptionModelModules } from './voloAbpHttpModelingApplicationApiDescriptionModelModules';
import type { VoloAbpHttpModelingApplicationApiDescriptionModelTypes } from './voloAbpHttpModelingApplicationApiDescriptionModelTypes';

export interface VoloAbpHttpModelingApplicationApiDescriptionModel {
  /** @nullable */
  modules?: VoloAbpHttpModelingApplicationApiDescriptionModelModules;
  /** @nullable */
  types?: VoloAbpHttpModelingApplicationApiDescriptionModelTypes;
}
