/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto {
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  englishName?: string | null;
  /** @nullable */
  threeLetterIsoLanguageName?: string | null;
  /** @nullable */
  twoLetterIsoLanguageName?: string | null;
  isRightToLeft?: boolean;
  /** @nullable */
  cultureName?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  nativeName?: string | null;
  dateTimeFormat?: VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto;
}
