/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type VoloAbpAccountWebAreasAccountControllersModelsLoginResultType = typeof VoloAbpAccountWebAreasAccountControllersModelsLoginResultType[keyof typeof VoloAbpAccountWebAreasAccountControllersModelsLoginResultType];


export const VoloAbpAccountWebAreasAccountControllersModelsLoginResultType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;
