/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto {
  /** @nullable */
  texts?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDtoTexts;
  /** @nullable */
  baseResources?: string[] | null;
}
