/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto';

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDto} | null;
