/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentUserDto {
  isAuthenticated?: boolean;
  /** @nullable */
  id?: string | null;
  /** @nullable */
  tenantId?: string | null;
  /** @nullable */
  impersonatorUserId?: string | null;
  /** @nullable */
  impersonatorTenantId?: string | null;
  /** @nullable */
  impersonatorUserName?: string | null;
  /** @nullable */
  impersonatorTenantName?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surName?: string | null;
  /** @nullable */
  email?: string | null;
  emailVerified?: boolean;
  /** @nullable */
  phoneNumber?: string | null;
  phoneNumberVerified?: boolean;
  /** @nullable */
  roles?: string[] | null;
  /** @nullable */
  sessionId?: string | null;
}
