/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpHttpModelingMethodParameterApiDescriptionModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  typeAsString?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  typeSimple?: string | null;
  isOptional?: boolean;
  defaultValue?: unknown;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  displayName?: string | null;
}
