/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpPermissionManagementResourcePermissionWithProdiverGrantInfoDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  providers?: string[] | null;
  isGranted?: boolean;
}
