/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementSearchProviderKeyInfo } from './voloAbpPermissionManagementSearchProviderKeyInfo';

export interface VoloAbpPermissionManagementSearchProviderKeyListResultDto {
  /** @nullable */
  keys?: VoloAbpPermissionManagementSearchProviderKeyInfo[] | null;
}
