/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpFeatureManagementFeatureProviderDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  key?: string | null;
}
