/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementUpdatePermissionDto } from './voloAbpPermissionManagementUpdatePermissionDto';

export interface VoloAbpPermissionManagementUpdatePermissionsDto {
  /** @nullable */
  permissions?: VoloAbpPermissionManagementUpdatePermissionDto[] | null;
}
