/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementResourcePermissionWithProdiverGrantInfoDto } from './voloAbpPermissionManagementResourcePermissionWithProdiverGrantInfoDto';

export interface VoloAbpPermissionManagementGetResourcePermissionWithProviderListResultDto {
  /** @nullable */
  permissions?: VoloAbpPermissionManagementResourcePermissionWithProdiverGrantInfoDto[] | null;
}
