/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpNameValue {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  value?: string | null;
}
