/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsDateTimeFormatDto {
  /** @nullable */
  calendarAlgorithmType?: string | null;
  /** @nullable */
  dateTimeFormatLong?: string | null;
  /** @nullable */
  shortDatePattern?: string | null;
  /** @nullable */
  fullDateTimePattern?: string | null;
  /** @nullable */
  dateSeparator?: string | null;
  /** @nullable */
  shortTimePattern?: string | null;
  /** @nullable */
  longTimePattern?: string | null;
}
