/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpSettingManagementEmailSettingsDto {
  /** @nullable */
  smtpHost?: string | null;
  smtpPort?: number;
  /** @nullable */
  smtpUserName?: string | null;
  /** @nullable */
  smtpPassword?: string | null;
  /** @nullable */
  smtpDomain?: string | null;
  smtpEnableSsl?: boolean;
  smtpUseDefaultCredentials?: boolean;
  /** @nullable */
  defaultFromAddress?: string | null;
  /** @nullable */
  defaultFromDisplayName?: string | null;
}
