/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementResourcePermissionDefinitionDto } from './voloAbpPermissionManagementResourcePermissionDefinitionDto';

export interface VoloAbpPermissionManagementGetResourcePermissionDefinitionListResultDto {
  /** @nullable */
  permissions?: VoloAbpPermissionManagementResourcePermissionDefinitionDto[] | null;
}
