/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type VoloAbpMultiTenancyTenantUserSharingStrategy = typeof VoloAbpMultiTenancyTenantUserSharingStrategy[keyof typeof VoloAbpMultiTenancyTenantUserSharingStrategy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VoloAbpMultiTenancyTenantUserSharingStrategy = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
