/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpPermissionManagementUpdateResourcePermissionsDto {
  /** @nullable */
  providerName?: string | null;
  /** @nullable */
  providerKey?: string | null;
  /** @nullable */
  permissions?: string[] | null;
}
