/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpPermissionManagementProviderInfoDto {
  /** @nullable */
  providerName?: string | null;
  /** @nullable */
  providerKey?: string | null;
}
