/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type VoloAbpAccountProfileDtoExtraProperties = {[key: string]: unknown} | null;
