/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementResourcePermissionGrantInfoDto } from './voloAbpPermissionManagementResourcePermissionGrantInfoDto';

export interface VoloAbpPermissionManagementGetResourcePermissionListResultDto {
  /** @nullable */
  permissions?: VoloAbpPermissionManagementResourcePermissionGrantInfoDto[] | null;
}
