/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountRegisterDtoExtraProperties } from './voloAbpAccountRegisterDtoExtraProperties';

export interface VoloAbpAccountRegisterDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpAccountRegisterDtoExtraProperties;
  /**
     * @minLength 0
     * @maxLength 256
     */
  userName: string;
  /**
     * @minLength 0
     * @maxLength 256
     */
  emailAddress: string;
  /**
     * @minLength 0
     * @maxLength 128
     */
  password: string;
  /** @minLength 1 */
  appName: string;
}
