/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDtoValues = {[key: string]: string | null} | null;
