/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantUpdateDtoExtraProperties } from './voloAbpTenantManagementTenantUpdateDtoExtraProperties';

export interface VoloAbpTenantManagementTenantUpdateDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpTenantManagementTenantUpdateDtoExtraProperties;
  /**
   * @minLength 0
   * @maxLength 64
   */
  name: string;
  /** @nullable */
  concurrencyStamp?: string | null;
}
