/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDtoValues } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDtoValues';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDto {
  /** @nullable */
  values?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationFeatureConfigurationDtoValues;
}
