/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingTypeApiDescriptionModel } from './voloAbpHttpModelingTypeApiDescriptionModel';

/**
 * @nullable
 */
export type VoloAbpHttpModelingApplicationApiDescriptionModelTypes = {[key: string]: VoloAbpHttpModelingTypeApiDescriptionModel} | null;
