/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAccountResetPasswordDto {
  userId?: string;
  /** @minLength 1 */
  resetToken: string;
  /** @minLength 1 */
  password: string;
}
