/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpNameValue } from './voloAbpNameValue';

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguageFilesMap = {[key: string]: VoloAbpNameValue[]} | null;
