/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyUiLookupDto {
  /** @nullable */
  url?: string | null;
  /** @nullable */
  resultListPropertyName?: string | null;
  /** @nullable */
  displayPropertyName?: string | null;
  /** @nullable */
  valuePropertyName?: string | null;
  /** @nullable */
  filterParamName?: string | null;
}
