/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsIanaTimeZone {
  /** @nullable */
  timeZoneName?: string | null;
}
