/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityRoleUpdateDtoExtraProperties } from './voloAbpIdentityIdentityRoleUpdateDtoExtraProperties';

export interface VoloAbpIdentityIdentityRoleUpdateDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpIdentityIdentityRoleUpdateDtoExtraProperties;
  /**
     * @minLength 0
     * @maxLength 256
     */
  name: string;
  isDefault?: boolean;
  isPublic?: boolean;
  /** @nullable */
  concurrencyStamp?: string | null;
}
