/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpSettingManagementSendTestEmailInput {
  /** @minLength 1 */
  senderEmailAddress: string;
  /** @minLength 1 */
  targetEmailAddress: string;
  /** @minLength 1 */
  subject: string;
  /** @nullable */
  body?: string | null;
}
