/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcMultiTenancyCurrentTenantDto {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  isAvailable?: boolean;
}
