/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpValidationStringValuesIValueValidatorProperties } from './voloAbpValidationStringValuesIValueValidatorProperties';

export interface VoloAbpValidationStringValuesIValueValidator {
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly properties?: VoloAbpValidationStringValuesIValueValidatorProperties;
}
