/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpFeatureManagementFeatureGroupDto } from './voloAbpFeatureManagementFeatureGroupDto';

export interface VoloAbpFeatureManagementGetFeatureListResultDto {
  /** @nullable */
  groups?: VoloAbpFeatureManagementFeatureGroupDto[] | null;
}
