/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementPermissionGrantInfoDto } from './voloAbpPermissionManagementPermissionGrantInfoDto';

export interface VoloAbpPermissionManagementPermissionGroupDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  displayNameKey?: string | null;
  /** @nullable */
  displayNameResource?: string | null;
  /** @nullable */
  permissions?: VoloAbpPermissionManagementPermissionGrantInfoDto[] | null;
}
