/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto';

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoResources = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationResourceDto} | null;
