/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantDtoExtraProperties } from './voloAbpTenantManagementTenantDtoExtraProperties';

export interface VoloAbpTenantManagementTenantDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpTenantManagementTenantDtoExtraProperties;
  id?: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
}
