/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsClockDto {
  /** @nullable */
  kind?: string | null;
}
