/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumFieldDtoValue } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumFieldDtoValue';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumFieldDto {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  value?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionEnumFieldDtoValue;
}
