/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountProfileDtoExtraProperties } from './voloAbpAccountProfileDtoExtraProperties';

export interface VoloAbpAccountProfileDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpAccountProfileDtoExtraProperties;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  surname?: string | null;
  /** @nullable */
  phoneNumber?: string | null;
  isExternal?: boolean;
  hasPassword?: boolean;
  /** @nullable */
  concurrencyStamp?: string | null;
}
