/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpLocalizationLanguageInfo {
  /** @nullable */
  cultureName?: string | null;
  /** @nullable */
  uiCultureName?: string | null;
  /** @nullable */
  displayName?: string | null;
  /** @nullable */
  readonly twoLetterISOLanguageName?: string | null;
}
