/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguageFilesMap } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguageFilesMap';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguagesMap } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguagesMap';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoResources } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoResources';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoValues } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoValues';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto';
import type { VoloAbpLocalizationLanguageInfo } from './voloAbpLocalizationLanguageInfo';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDto {
  /** @nullable */
  values?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoValues;
  /** @nullable */
  resources?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoResources;
  /** @nullable */
  languages?: VoloAbpLocalizationLanguageInfo[] | null;
  currentCulture?: VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto;
  /** @nullable */
  defaultResourceName?: string | null;
  /** @nullable */
  languagesMap?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguagesMap;
  /** @nullable */
  languageFilesMap?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationConfigurationDtoLanguageFilesMap;
  useRouteBasedCulture?: boolean;
}
