/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAccountWebAreasAccountControllersModelsUserLoginInfo {
  /**
     * @minLength 0
     * @maxLength 255
     */
  userNameOrEmailAddress: string;
  /**
     * @minLength 0
     * @maxLength 32
     */
  password: string;
  rememberMe?: boolean;
}
