/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpPermissionManagementSearchProviderKeyInfo {
  /** @nullable */
  providerKey?: string | null;
  /** @nullable */
  providerDisplayName?: string | null;
}
