/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingModuleApiDescriptionModelControllers } from './voloAbpHttpModelingModuleApiDescriptionModelControllers';

export interface VoloAbpHttpModelingModuleApiDescriptionModel {
  /** @nullable */
  rootPath?: string | null;
  /** @nullable */
  remoteServiceName?: string | null;
  /** @nullable */
  controllers?: VoloAbpHttpModelingModuleApiDescriptionModelControllers;
}
