/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAccountWebAreasAccountControllersModelsLoginResultType } from './voloAbpAccountWebAreasAccountControllersModelsLoginResultType';

export interface VoloAbpAccountWebAreasAccountControllersModelsAbpLoginResult {
  result?: VoloAbpAccountWebAreasAccountControllersModelsLoginResultType;
  /** @nullable */
  readonly description?: string | null;
}
