/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpIdentityIdentityUserUpdateDtoExtraProperties } from './voloAbpIdentityIdentityUserUpdateDtoExtraProperties';

export interface VoloAbpIdentityIdentityUserUpdateDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpIdentityIdentityUserUpdateDtoExtraProperties;
  /**
   * @minLength 0
   * @maxLength 256
   */
  userName: string;
  /**
   * @minLength 0
   * @maxLength 64
   * @nullable
   */
  name?: string | null;
  /**
   * @minLength 0
   * @maxLength 64
   * @nullable
   */
  surname?: string | null;
  /**
   * @minLength 0
   * @maxLength 256
   */
  email: string;
  /**
   * @minLength 0
   * @maxLength 16
   * @nullable
   */
  phoneNumber?: string | null;
  isActive?: boolean;
  lockoutEnabled?: boolean;
  /** @nullable */
  roleNames?: string[] | null;
  /**
   * @minLength 0
   * @maxLength 128
   * @nullable
   */
  password?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
}
