/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto';

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingExtensionPropertyDto} | null;
