/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingParameterApiDescriptionModelDefaultValue } from './voloAbpHttpModelingParameterApiDescriptionModelDefaultValue';

export interface VoloAbpHttpModelingParameterApiDescriptionModel {
  /** @nullable */
  nameOnMethod?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  jsonName?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  typeSimple?: string | null;
  isOptional?: boolean;
  /** @nullable */
  defaultValue?: VoloAbpHttpModelingParameterApiDescriptionModelDefaultValue;
  /** @nullable */
  constraintTypes?: string[] | null;
  /** @nullable */
  bindingSourceId?: string | null;
  /** @nullable */
  descriptorName?: string | null;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  displayName?: string | null;
}
