/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingInterfaceMethodApiDescriptionModel } from './voloAbpHttpModelingInterfaceMethodApiDescriptionModel';

export interface VoloAbpHttpModelingControllerInterfaceApiDescriptionModel {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  methods?: VoloAbpHttpModelingInterfaceMethodApiDescriptionModel[] | null;
}
