/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpTenantManagementTenantCreateDtoExtraProperties } from './voloAbpTenantManagementTenantCreateDtoExtraProperties';

export interface VoloAbpTenantManagementTenantCreateDto {
  /** @nullable */
  readonly extraProperties?: VoloAbpTenantManagementTenantCreateDtoExtraProperties;
  /**
   * @minLength 0
   * @maxLength 64
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 256
   */
  adminEmailAddress: string;
  /**
   * @minLength 1
   * @maxLength 128
   */
  adminPassword: string;
}
