/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDto {
  /** @nullable */
  modules?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoModules;
  /** @nullable */
  enums?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingObjectExtensionsDtoEnums;
}
