/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue } from './voloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue';

export interface VoloAbpHttpModelingMethodParameterApiDescriptionModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  typeAsString?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  typeSimple?: string | null;
  isOptional?: boolean;
  /** @nullable */
  defaultValue?: VoloAbpHttpModelingMethodParameterApiDescriptionModelDefaultValue;
  /** @nullable */
  summary?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  displayName?: string | null;
}
