/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingMethodParameterApiDescriptionModel } from './voloAbpHttpModelingMethodParameterApiDescriptionModel';
import type { VoloAbpHttpModelingReturnValueApiDescriptionModel } from './voloAbpHttpModelingReturnValueApiDescriptionModel';

export interface VoloAbpHttpModelingInterfaceMethodApiDescriptionModel {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  parametersOnMethod?: VoloAbpHttpModelingMethodParameterApiDescriptionModel[] | null;
  returnValue?: VoloAbpHttpModelingReturnValueApiDescriptionModel;
}
