/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpValidationStringValuesIStringValueTypeProperties } from './voloAbpValidationStringValuesIStringValueTypeProperties';
import type { VoloAbpValidationStringValuesIValueValidator } from './voloAbpValidationStringValuesIValueValidator';

export interface VoloAbpValidationStringValuesIStringValueType {
  /** @nullable */
  readonly name?: string | null;
  /** @nullable */
  readonly properties?: VoloAbpValidationStringValuesIStringValueTypeProperties;
  validator?: VoloAbpValidationStringValuesIValueValidator;
}
