/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpPermissionManagementUpdatePermissionDto {
  /** @nullable */
  name?: string | null;
  isGranted?: boolean;
}
