/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpRemoteServiceErrorInfoData } from './voloAbpHttpRemoteServiceErrorInfoData';
import type { VoloAbpHttpRemoteServiceValidationErrorInfo } from './voloAbpHttpRemoteServiceValidationErrorInfo';

export interface VoloAbpHttpRemoteServiceErrorInfo {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
  /** @nullable */
  details?: string | null;
  /** @nullable */
  data?: VoloAbpHttpRemoteServiceErrorInfoData;
  /** @nullable */
  validationErrors?: VoloAbpHttpRemoteServiceValidationErrorInfo[] | null;
}
