/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export type VoloAbpMultiTenancyTenantUserSharingStrategy = typeof VoloAbpMultiTenancyTenantUserSharingStrategy[keyof typeof VoloAbpMultiTenancyTenantUserSharingStrategy];


export const VoloAbpMultiTenancyTenantUserSharingStrategy = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
