/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpHttpModelingControllerApiDescriptionModel } from './voloAbpHttpModelingControllerApiDescriptionModel';

/**
 * @nullable
 */
export type VoloAbpHttpModelingModuleApiDescriptionModelControllers = {[key: string]: VoloAbpHttpModelingControllerApiDescriptionModel} | null;
