/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDtoGrantedPolicies } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDtoGrantedPolicies';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDto {
  /** @nullable */
  grantedPolicies?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDtoGrantedPolicies;
}
