/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationAuthConfigurationDtoGrantedPolicies = {[key: string]: boolean} | null;
