/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto {
  /** @nullable */
  properties?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoProperties;
  /** @nullable */
  configuration?: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDtoConfiguration;
}
