/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpHttpModelingAuthorizeDataApiDescriptionModel {
  /** @nullable */
  policy?: string | null;
  /** @nullable */
  roles?: string | null;
}
