/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto';

/**
 * @nullable
 */
export type VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingModuleExtensionDtoEntities = {[key: string]: VoloAbpAspNetCoreMvcApplicationConfigurationsObjectExtendingEntityExtensionDto} | null;
