/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources } from './voloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources';
import type { VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto } from './voloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto';

export interface VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto {
  /** @nullable */
  resources?: VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDtoResources;
  currentCulture?: VoloAbpAspNetCoreMvcApplicationConfigurationsCurrentCultureDto;
}
