/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import type { VoloAbpPermissionManagementResourceProviderDto } from './voloAbpPermissionManagementResourceProviderDto';

export interface VoloAbpPermissionManagementGetResourceProviderListResultDto {
  /** @nullable */
  providers?: VoloAbpPermissionManagementResourceProviderDto[] | null;
}
