/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */

export interface VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto {
  success?: boolean;
  /** @nullable */
  tenantId?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  normalizedName?: string | null;
  isActive?: boolean;
}
