/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiSettingManagementEmailingResponse = zod.object({
  "smtpHost": zod.string().nullish(),
  "smtpPort": zod.number().optional(),
  "smtpUserName": zod.string().nullish(),
  "smtpPassword": zod.string().nullish(),
  "smtpDomain": zod.string().nullish(),
  "smtpEnableSsl": zod.boolean().optional(),
  "smtpUseDefaultCredentials": zod.boolean().optional(),
  "defaultFromAddress": zod.string().nullish(),
  "defaultFromDisplayName": zod.string().nullish()
})

export const postApiSettingManagementEmailingBodySmtpHostMax = 256;

export const postApiSettingManagementEmailingBodySmtpPortMax = 65535;

export const postApiSettingManagementEmailingBodySmtpUserNameMax = 1024;

export const postApiSettingManagementEmailingBodySmtpPasswordMax = 1024;

export const postApiSettingManagementEmailingBodySmtpDomainMax = 1024;

export const postApiSettingManagementEmailingBodyDefaultFromAddressMax = 1024;

export const postApiSettingManagementEmailingBodyDefaultFromDisplayNameMax = 1024;



export const postApiSettingManagementEmailingBody = zod.object({
  "smtpHost": zod.string().max(postApiSettingManagementEmailingBodySmtpHostMax).nullish(),
  "smtpPort": zod.number().min(1).max(postApiSettingManagementEmailingBodySmtpPortMax).optional(),
  "smtpUserName": zod.string().max(postApiSettingManagementEmailingBodySmtpUserNameMax).nullish(),
  "smtpPassword": zod.string().max(postApiSettingManagementEmailingBodySmtpPasswordMax).nullish(),
  "smtpDomain": zod.string().max(postApiSettingManagementEmailingBodySmtpDomainMax).nullish(),
  "smtpEnableSsl": zod.boolean().optional(),
  "smtpUseDefaultCredentials": zod.boolean().optional(),
  "defaultFromAddress": zod.string().min(1).max(postApiSettingManagementEmailingBodyDefaultFromAddressMax),
  "defaultFromDisplayName": zod.string().min(1).max(postApiSettingManagementEmailingBodyDefaultFromDisplayNameMax)
})






export const postApiSettingManagementEmailingSendTestEmailBody = zod.object({
  "senderEmailAddress": zod.string().min(1),
  "targetEmailAddress": zod.string().min(1),
  "subject": zod.string().min(1),
  "body": zod.string().nullish()
})

