/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiAbpApplicationLocalizationParams,
  VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiAbpApplicationLocalizationUrl = (params: GetApiAbpApplicationLocalizationParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/abp/application-localization?${stringifiedParams}` : `/api/abp/application-localization`
}

export const getApiAbpApplicationLocalization = async (params: GetApiAbpApplicationLocalizationParams, options?: RequestInit): Promise<VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto> => {
  
  return abpMutator<VoloAbpAspNetCoreMvcApplicationConfigurationsApplicationLocalizationDto>(getGetApiAbpApplicationLocalizationUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiAbpApplicationLocalizationQueryKey = (params?: GetApiAbpApplicationLocalizationParams,) => {
    return [
    `/api/abp/application-localization`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiAbpApplicationLocalizationQueryOptions = <TData = Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params: GetApiAbpApplicationLocalizationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAbpApplicationLocalizationQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>> = ({ signal }) => getApiAbpApplicationLocalization(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiAbpApplicationLocalizationQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>>
export type GetApiAbpApplicationLocalizationQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAbpApplicationLocalization<TData = Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: GetApiAbpApplicationLocalizationParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAbpApplicationLocalization<TData = Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: GetApiAbpApplicationLocalizationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiAbpApplicationLocalization<TData = Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: GetApiAbpApplicationLocalizationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiAbpApplicationLocalization<TData = Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: GetApiAbpApplicationLocalizationParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpApplicationLocalization>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiAbpApplicationLocalizationQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




