/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  PostApiSettingManagementTimezoneParams,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpNameValue
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiSettingManagementTimezoneUrl = () => {


  

  return `/api/setting-management/timezone`
}

export const getApiSettingManagementTimezone = async ( options?: RequestInit): Promise<string> => {
  
  return abpMutator<string>(getGetApiSettingManagementTimezoneUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiSettingManagementTimezoneQueryKey = () => {
    return [
    `/api/setting-management/timezone`
    ] as const;
    }

    
export const getGetApiSettingManagementTimezoneQueryOptions = <TData = Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSettingManagementTimezoneQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>> = ({ signal }) => getApiSettingManagementTimezone({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiSettingManagementTimezoneQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>>
export type GetApiSettingManagementTimezoneQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiSettingManagementTimezone<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementTimezone>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementTimezone>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiSettingManagementTimezone<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementTimezone>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementTimezone>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiSettingManagementTimezone<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiSettingManagementTimezone<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezone>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiSettingManagementTimezoneQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiSettingManagementTimezoneUrl = (params?: PostApiSettingManagementTimezoneParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/setting-management/timezone?${stringifiedParams}` : `/api/setting-management/timezone`
}

export const postApiSettingManagementTimezone = async (params?: PostApiSettingManagementTimezoneParams, options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getPostApiSettingManagementTimezoneUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPostApiSettingManagementTimezoneMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementTimezone>>, TError,{params?: PostApiSettingManagementTimezoneParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementTimezone>>, TError,{params?: PostApiSettingManagementTimezoneParams}, TContext> => {

const mutationKey = ['postApiSettingManagementTimezone'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSettingManagementTimezone>>, {params?: PostApiSettingManagementTimezoneParams}> = (props) => {
          const {params} = props ?? {};

          return  postApiSettingManagementTimezone(params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiSettingManagementTimezoneMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSettingManagementTimezone>>>
    
    export type PostApiSettingManagementTimezoneMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiSettingManagementTimezone = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementTimezone>>, TError,{params?: PostApiSettingManagementTimezoneParams}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSettingManagementTimezone>>,
        TError,
        {params?: PostApiSettingManagementTimezoneParams},
        TContext
      > => {

      const mutationOptions = getPostApiSettingManagementTimezoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getGetApiSettingManagementTimezoneTimezonesUrl = () => {


  

  return `/api/setting-management/timezone/timezones`
}

export const getApiSettingManagementTimezoneTimezones = async ( options?: RequestInit): Promise<VoloAbpNameValue[]> => {
  
  return abpMutator<VoloAbpNameValue[]>(getGetApiSettingManagementTimezoneTimezonesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiSettingManagementTimezoneTimezonesQueryKey = () => {
    return [
    `/api/setting-management/timezone/timezones`
    ] as const;
    }

    
export const getGetApiSettingManagementTimezoneTimezonesQueryOptions = <TData = Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSettingManagementTimezoneTimezonesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>> = ({ signal }) => getApiSettingManagementTimezoneTimezones({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiSettingManagementTimezoneTimezonesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>>
export type GetApiSettingManagementTimezoneTimezonesQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiSettingManagementTimezoneTimezones<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiSettingManagementTimezoneTimezones<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiSettingManagementTimezoneTimezones<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiSettingManagementTimezoneTimezones<TData = Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementTimezoneTimezones>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiSettingManagementTimezoneTimezonesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




