/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAbpApplicationConfigurationQueryParams = zod.object({
  "IncludeLocalizationResources": zod.boolean().optional()
})

export const getApiAbpApplicationConfigurationResponse = zod.object({
  "localization": zod.object({
  "values": zod.record(zod.string(), zod.record(zod.string(), zod.string())).nullish(),
  "resources": zod.record(zod.string(), zod.object({
  "texts": zod.record(zod.string(), zod.string()).nullish(),
  "baseResources": zod.array(zod.string()).nullish()
})).nullish(),
  "languages": zod.array(zod.object({
  "cultureName": zod.string().nullish(),
  "uiCultureName": zod.string().nullish(),
  "displayName": zod.string().nullish(),
  "twoLetterISOLanguageName": zod.string().nullish()
})).nullish(),
  "currentCulture": zod.object({
  "displayName": zod.string().nullish(),
  "englishName": zod.string().nullish(),
  "threeLetterIsoLanguageName": zod.string().nullish(),
  "twoLetterIsoLanguageName": zod.string().nullish(),
  "isRightToLeft": zod.boolean().optional(),
  "cultureName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "nativeName": zod.string().nullish(),
  "dateTimeFormat": zod.object({
  "calendarAlgorithmType": zod.string().nullish(),
  "dateTimeFormatLong": zod.string().nullish(),
  "shortDatePattern": zod.string().nullish(),
  "fullDateTimePattern": zod.string().nullish(),
  "dateSeparator": zod.string().nullish(),
  "shortTimePattern": zod.string().nullish(),
  "longTimePattern": zod.string().nullish()
}).optional()
}).optional(),
  "defaultResourceName": zod.string().nullish(),
  "languagesMap": zod.record(zod.string(), zod.array(zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
}))).nullish(),
  "languageFilesMap": zod.record(zod.string(), zod.array(zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
}))).nullish(),
  "useRouteBasedCulture": zod.boolean().optional()
}).optional(),
  "auth": zod.object({
  "grantedPolicies": zod.record(zod.string(), zod.boolean()).nullish()
}).optional(),
  "setting": zod.object({
  "values": zod.record(zod.string(), zod.string().nullable()).nullish()
}).optional(),
  "currentUser": zod.object({
  "isAuthenticated": zod.boolean().optional(),
  "id": zod.uuid().nullish(),
  "tenantId": zod.uuid().nullish(),
  "impersonatorUserId": zod.uuid().nullish(),
  "impersonatorTenantId": zod.uuid().nullish(),
  "impersonatorUserName": zod.string().nullish(),
  "impersonatorTenantName": zod.string().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surName": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailVerified": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberVerified": zod.boolean().optional(),
  "roles": zod.array(zod.string()).nullish(),
  "sessionId": zod.string().nullish()
}).optional(),
  "features": zod.object({
  "values": zod.record(zod.string(), zod.string().nullable()).nullish()
}).optional(),
  "globalFeatures": zod.object({
  "enabledFeatures": zod.array(zod.string()).nullish()
}).optional(),
  "multiTenancy": zod.object({
  "isEnabled": zod.boolean().optional(),
  "userSharingStrategy": zod.union([zod.literal(0),zod.literal(1)]).optional()
}).optional(),
  "currentTenant": zod.object({
  "id": zod.uuid().nullish(),
  "name": zod.string().nullish(),
  "isAvailable": zod.boolean().optional()
}).optional(),
  "timing": zod.object({
  "timeZone": zod.object({
  "iana": zod.object({
  "timeZoneName": zod.string().nullish()
}).optional(),
  "windows": zod.object({
  "timeZoneId": zod.string().nullish()
}).optional()
}).optional()
}).optional(),
  "clock": zod.object({
  "kind": zod.string().nullish()
}).optional(),
  "objectExtensions": zod.object({
  "modules": zod.record(zod.string(), zod.object({
  "entities": zod.record(zod.string(), zod.object({
  "properties": zod.record(zod.string(), zod.object({
  "type": zod.string().nullish(),
  "typeSimple": zod.string().nullish(),
  "displayName": zod.object({
  "name": zod.string().nullish(),
  "resource": zod.string().nullish()
}).optional(),
  "api": zod.object({
  "onGet": zod.object({
  "isAvailable": zod.boolean().optional()
}).optional(),
  "onCreate": zod.object({
  "isAvailable": zod.boolean().optional()
}).optional(),
  "onUpdate": zod.object({
  "isAvailable": zod.boolean().optional()
}).optional()
}).optional(),
  "ui": zod.object({
  "onTable": zod.object({
  "isVisible": zod.boolean().optional()
}).optional(),
  "onCreateForm": zod.object({
  "isVisible": zod.boolean().optional()
}).optional(),
  "onEditForm": zod.object({
  "isVisible": zod.boolean().optional()
}).optional(),
  "lookup": zod.object({
  "url": zod.string().nullish(),
  "resultListPropertyName": zod.string().nullish(),
  "displayPropertyName": zod.string().nullish(),
  "valuePropertyName": zod.string().nullish(),
  "filterParamName": zod.string().nullish()
}).optional()
}).optional(),
  "policy": zod.object({
  "globalFeatures": zod.object({
  "features": zod.array(zod.string()).nullish(),
  "requiresAll": zod.boolean().optional()
}).optional(),
  "features": zod.object({
  "features": zod.array(zod.string()).nullish(),
  "requiresAll": zod.boolean().optional()
}).optional(),
  "permissions": zod.object({
  "permissionNames": zod.array(zod.string()).nullish(),
  "requiresAll": zod.boolean().optional()
}).optional()
}).optional(),
  "attributes": zod.array(zod.object({
  "typeSimple": zod.string().nullish(),
  "config": zod.record(zod.string(), zod.unknown()).nullish()
})).nullish(),
  "configuration": zod.record(zod.string(), zod.unknown()).nullish(),
  "defaultValue": zod.unknown().nullish()
})).nullish(),
  "configuration": zod.record(zod.string(), zod.unknown()).nullish()
})).nullish(),
  "configuration": zod.record(zod.string(), zod.unknown()).nullish()
})).nullish(),
  "enums": zod.record(zod.string(), zod.object({
  "fields": zod.array(zod.object({
  "name": zod.string().nullish(),
  "value": zod.unknown().nullish()
})).nullish(),
  "localizationResource": zod.string().nullish()
})).nullish()
}).optional(),
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish()
})

