/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiSettingManagementTimezoneResponse = zod.string()

export const PostApiSettingManagementTimezoneQueryParams = zod.object({
  "timezone": zod.string().optional()
})

export const PostApiSettingManagementTimezoneResponse = zod.unknown()

export const GetApiSettingManagementTimezoneTimezonesResponseItem = zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
})
export const GetApiSettingManagementTimezoneTimezonesResponse = zod.array(GetApiSettingManagementTimezoneTimezonesResponseItem)

