/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiSettingManagementTimezoneResponse = zod.string()

export const postApiSettingManagementTimezoneQueryParams = zod.object({
  "timezone": zod.string().optional()
})

export const getApiSettingManagementTimezoneTimezonesResponseItem = zod.object({
  "name": zod.string().nullish(),
  "value": zod.string().nullish()
})
export const getApiSettingManagementTimezoneTimezonesResponse = zod.array(getApiSettingManagementTimezoneTimezonesResponseItem)

