/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto,
  VoloAbpHttpRemoteServiceErrorResponse
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetApiAbpMultiTenancyTenantsByNameNameUrl = (name: string,) => {




  return `/api/abp/multi-tenancy/tenants/by-name/${name}`
}

export const getApiAbpMultiTenancyTenantsByNameName = async (name: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto> => {

  return abpMutator<VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto>(getGetApiAbpMultiTenancyTenantsByNameNameUrl(name),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAbpMultiTenancyTenantsByNameNameQueryKey = (name: string,) => {
    return [
    `/api/abp/multi-tenancy/tenants/by-name/${name}`
    ] as const;
    }


export const getGetApiAbpMultiTenancyTenantsByNameNameQueryOptions = <TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAbpMultiTenancyTenantsByNameNameQueryKey(name);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>> = ({ signal }) => getApiAbpMultiTenancyTenantsByNameName(name, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: name !== null && name !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAbpMultiTenancyTenantsByNameNameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>>
export type GetApiAbpMultiTenancyTenantsByNameNameQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAbpMultiTenancyTenantsByNameName<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAbpMultiTenancyTenantsByNameName<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAbpMultiTenancyTenantsByNameName<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAbpMultiTenancyTenantsByNameName<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByNameName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAbpMultiTenancyTenantsByNameNameQueryOptions(name,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGetApiAbpMultiTenancyTenantsByIdIdUrl = (id: string,) => {




  return `/api/abp/multi-tenancy/tenants/by-id/${id}`
}

export const getApiAbpMultiTenancyTenantsByIdId = async (id: string, options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto> => {

  return abpMutator<VoloAbpAspNetCoreMvcMultiTenancyFindTenantResultDto>(getGetApiAbpMultiTenancyTenantsByIdIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAbpMultiTenancyTenantsByIdIdQueryKey = (id: string,) => {
    return [
    `/api/abp/multi-tenancy/tenants/by-id/${id}`
    ] as const;
    }


export const getGetApiAbpMultiTenancyTenantsByIdIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAbpMultiTenancyTenantsByIdIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>> = ({ signal }) => getApiAbpMultiTenancyTenantsByIdId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAbpMultiTenancyTenantsByIdIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>>
export type GetApiAbpMultiTenancyTenantsByIdIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiAbpMultiTenancyTenantsByIdId<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAbpMultiTenancyTenantsByIdId<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>,
          TError,
          Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAbpMultiTenancyTenantsByIdId<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAbpMultiTenancyTenantsByIdId<TData = Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAbpMultiTenancyTenantsByIdId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAbpMultiTenancyTenantsByIdIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






