/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiIdentityRolesParams,
  ListResultDtoOfIdentityRoleDto,
  PagedResultDtoOfIdentityRoleDto,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpIdentityIdentityRoleCreateDto,
  VoloAbpIdentityIdentityRoleDto,
  VoloAbpIdentityIdentityRoleUpdateDto
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiIdentityRolesAllUrl = () => {


  

  return `/api/identity/roles/all`
}

export const getApiIdentityRolesAll = async ( options?: RequestInit): Promise<ListResultDtoOfIdentityRoleDto> => {
  
  return abpMutator<ListResultDtoOfIdentityRoleDto>(getGetApiIdentityRolesAllUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityRolesAllQueryKey = () => {
    return [
    `/api/identity/roles/all`
    ] as const;
    }

    
export const getGetApiIdentityRolesAllQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityRolesAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityRolesAll>>> = ({ signal }) => getApiIdentityRolesAll({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityRolesAllQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityRolesAll>>>
export type GetApiIdentityRolesAllQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityRolesAll<TData = Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRolesAll>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRolesAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRolesAll<TData = Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRolesAll>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRolesAll>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRolesAll<TData = Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityRolesAll<TData = Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesAll>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityRolesAllQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiIdentityRolesUrl = (params?: GetApiIdentityRolesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/identity/roles?${stringifiedParams}` : `/api/identity/roles`
}

export const getApiIdentityRoles = async (params?: GetApiIdentityRolesParams, options?: RequestInit): Promise<PagedResultDtoOfIdentityRoleDto> => {
  
  return abpMutator<PagedResultDtoOfIdentityRoleDto>(getGetApiIdentityRolesUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityRolesQueryKey = (params?: GetApiIdentityRolesParams,) => {
    return [
    `/api/identity/roles`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiIdentityRolesQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiIdentityRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityRolesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityRoles>>> = ({ signal }) => getApiIdentityRoles(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityRoles>>>
export type GetApiIdentityRolesQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityRoles<TData = Awaited<ReturnType<typeof getApiIdentityRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiIdentityRolesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRoles<TData = Awaited<ReturnType<typeof getApiIdentityRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRoles>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRoles<TData = Awaited<ReturnType<typeof getApiIdentityRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityRoles<TData = Awaited<ReturnType<typeof getApiIdentityRoles>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRoles>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityRolesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPostApiIdentityRolesUrl = () => {


  

  return `/api/identity/roles`
}

export const postApiIdentityRoles = async (voloAbpIdentityIdentityRoleCreateDto: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>, options?: RequestInit): Promise<VoloAbpIdentityIdentityRoleDto> => {
  
  return abpMutator<VoloAbpIdentityIdentityRoleDto>(getPostApiIdentityRolesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpIdentityIdentityRoleCreateDto,)
  }
);}




export const getPostApiIdentityRolesMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityRoles>>, TError,{data: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityRoles>>, TError,{data: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>}, TContext> => {

const mutationKey = ['postApiIdentityRoles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiIdentityRoles>>, {data: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>}> = (props) => {
          const {data} = props ?? {};

          return  postApiIdentityRoles(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiIdentityRolesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiIdentityRoles>>>
    export type PostApiIdentityRolesMutationBody = NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>
    export type PostApiIdentityRolesMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePostApiIdentityRoles = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiIdentityRoles>>, TError,{data: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiIdentityRoles>>,
        TError,
        {data: NonReadonly<VoloAbpIdentityIdentityRoleCreateDto>},
        TContext
      > => {

      const mutationOptions = getPostApiIdentityRolesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getGetApiIdentityRolesIdUrl = (id: string,) => {


  

  return `/api/identity/roles/${id}`
}

export const getApiIdentityRolesId = async (id: string, options?: RequestInit): Promise<VoloAbpIdentityIdentityRoleDto> => {
  
  return abpMutator<VoloAbpIdentityIdentityRoleDto>(getGetApiIdentityRolesIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityRolesIdQueryKey = (id?: string,) => {
    return [
    `/api/identity/roles/${id}`
    ] as const;
    }

    
export const getGetApiIdentityRolesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityRolesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityRolesId>>> = ({ signal }) => getApiIdentityRolesId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityRolesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityRolesId>>>
export type GetApiIdentityRolesIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityRolesId<TData = Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRolesId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRolesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRolesId<TData = Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityRolesId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityRolesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityRolesId<TData = Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityRolesId<TData = Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityRolesId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityRolesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getPutApiIdentityRolesIdUrl = (id: string,) => {


  

  return `/api/identity/roles/${id}`
}

export const putApiIdentityRolesId = async (id: string,
    voloAbpIdentityIdentityRoleUpdateDto: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>, options?: RequestInit): Promise<VoloAbpIdentityIdentityRoleDto> => {
  
  return abpMutator<VoloAbpIdentityIdentityRoleDto>(getPutApiIdentityRolesIdUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      voloAbpIdentityIdentityRoleUpdateDto,)
  }
);}




export const getPutApiIdentityRolesIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityRolesId>>, TError,{id: string;data: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityRolesId>>, TError,{id: string;data: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>}, TContext> => {

const mutationKey = ['putApiIdentityRolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiIdentityRolesId>>, {id: string;data: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiIdentityRolesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiIdentityRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiIdentityRolesId>>>
    export type PutApiIdentityRolesIdMutationBody = NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>
    export type PutApiIdentityRolesIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const usePutApiIdentityRolesId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiIdentityRolesId>>, TError,{id: string;data: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiIdentityRolesId>>,
        TError,
        {id: string;data: NonReadonly<VoloAbpIdentityIdentityRoleUpdateDto>},
        TContext
      > => {

      const mutationOptions = getPutApiIdentityRolesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const getDeleteApiIdentityRolesIdUrl = (id: string,) => {


  

  return `/api/identity/roles/${id}`
}

export const deleteApiIdentityRolesId = async (id: string, options?: RequestInit): Promise<void | void> => {
  
  return abpMutator<void | void>(getDeleteApiIdentityRolesIdUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteApiIdentityRolesIdMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityRolesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityRolesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiIdentityRolesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiIdentityRolesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiIdentityRolesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiIdentityRolesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiIdentityRolesId>>>
    
    export type DeleteApiIdentityRolesIdMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>

    export const useDeleteApiIdentityRolesId = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiIdentityRolesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiIdentityRolesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiIdentityRolesIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    