/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiIdentityUsersLookupCountParams,
  GetApiIdentityUsersLookupSearchParams,
  ListResultDtoOfUserData,
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpUsersUserData
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetApiIdentityUsersLookupIdUrl = (id: string,) => {


  

  return `/api/identity/users/lookup/${id}`
}

export const getApiIdentityUsersLookupId = async (id: string, options?: RequestInit): Promise<VoloAbpUsersUserData> => {
  
  return abpMutator<VoloAbpUsersUserData>(getGetApiIdentityUsersLookupIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityUsersLookupIdQueryKey = (id?: string,) => {
    return [
    `/api/identity/users/lookup/${id}`
    ] as const;
    }

    
export const getGetApiIdentityUsersLookupIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersLookupIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>> = ({ signal }) => getApiIdentityUsersLookupId(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityUsersLookupIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>>
export type GetApiIdentityUsersLookupIdQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersLookupId<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupId<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupId<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityUsersLookupId<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupId>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityUsersLookupIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiIdentityUsersLookupByUsernameUserNameUrl = (userName: string,) => {


  

  return `/api/identity/users/lookup/by-username/${userName}`
}

export const getApiIdentityUsersLookupByUsernameUserName = async (userName: string, options?: RequestInit): Promise<VoloAbpUsersUserData> => {
  
  return abpMutator<VoloAbpUsersUserData>(getGetApiIdentityUsersLookupByUsernameUserNameUrl(userName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityUsersLookupByUsernameUserNameQueryKey = (userName?: string,) => {
    return [
    `/api/identity/users/lookup/by-username/${userName}`
    ] as const;
    }

    
export const getGetApiIdentityUsersLookupByUsernameUserNameQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersLookupByUsernameUserNameQueryKey(userName);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>> = ({ signal }) => getApiIdentityUsersLookupByUsernameUserName(userName, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(userName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityUsersLookupByUsernameUserNameQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>>
export type GetApiIdentityUsersLookupByUsernameUserNameQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersLookupByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityUsersLookupByUsernameUserName<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 userName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupByUsernameUserName>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityUsersLookupByUsernameUserNameQueryOptions(userName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiIdentityUsersLookupSearchUrl = (params?: GetApiIdentityUsersLookupSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/identity/users/lookup/search?${stringifiedParams}` : `/api/identity/users/lookup/search`
}

export const getApiIdentityUsersLookupSearch = async (params?: GetApiIdentityUsersLookupSearchParams, options?: RequestInit): Promise<ListResultDtoOfUserData> => {
  
  return abpMutator<ListResultDtoOfUserData>(getGetApiIdentityUsersLookupSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityUsersLookupSearchQueryKey = (params?: GetApiIdentityUsersLookupSearchParams,) => {
    return [
    `/api/identity/users/lookup/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiIdentityUsersLookupSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiIdentityUsersLookupSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersLookupSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>> = ({ signal }) => getApiIdentityUsersLookupSearch(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityUsersLookupSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>>
export type GetApiIdentityUsersLookupSearchQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersLookupSearch<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiIdentityUsersLookupSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupSearch<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupSearch<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityUsersLookupSearch<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupSearch>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityUsersLookupSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiIdentityUsersLookupCountUrl = (params?: GetApiIdentityUsersLookupCountParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/identity/users/lookup/count?${stringifiedParams}` : `/api/identity/users/lookup/count`
}

export const getApiIdentityUsersLookupCount = async (params?: GetApiIdentityUsersLookupCountParams, options?: RequestInit): Promise<number> => {
  
  return abpMutator<number>(getGetApiIdentityUsersLookupCountUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetApiIdentityUsersLookupCountQueryKey = (params?: GetApiIdentityUsersLookupCountParams,) => {
    return [
    `/api/identity/users/lookup/count`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetApiIdentityUsersLookupCountQueryOptions = <TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(params?: GetApiIdentityUsersLookupCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiIdentityUsersLookupCountQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>> = ({ signal }) => getApiIdentityUsersLookupCount(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetApiIdentityUsersLookupCountQueryResult = NonNullable<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>>
export type GetApiIdentityUsersLookupCountQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiIdentityUsersLookupCount<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params: undefined |  GetApiIdentityUsersLookupCountParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupCount<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>,
          TError,
          Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetApiIdentityUsersLookupCount<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useGetApiIdentityUsersLookupCount<TData = Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
 params?: GetApiIdentityUsersLookupCountParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiIdentityUsersLookupCount>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetApiIdentityUsersLookupCountQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




