/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  VoloAbpHttpRemoteServiceErrorResponse,
  VoloAbpSettingManagementEmailSettingsDto,
  VoloAbpSettingManagementSendTestEmailInput,
  VoloAbpSettingManagementUpdateEmailSettingsDto
} from '../../models';

import { abpMutator } from '../../mutator';
import type { ErrorType } from '../../mutator';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetApiSettingManagementEmailingUrl = () => {




  return `/api/setting-management/emailing`
}

export const getApiSettingManagementEmailing = async ( options?: Parameters<typeof abpMutator>[1]): Promise<VoloAbpSettingManagementEmailSettingsDto> => {

  return abpMutator<VoloAbpSettingManagementEmailSettingsDto>(getGetApiSettingManagementEmailingUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiSettingManagementEmailingQueryKey = () => {
    return [
    `/api/setting-management/emailing`
    ] as const;
    }


export const getGetApiSettingManagementEmailingQueryOptions = <TData = Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiSettingManagementEmailingQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>> = ({ signal }) => getApiSettingManagementEmailing({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiSettingManagementEmailingQueryResult = NonNullable<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>>
export type GetApiSettingManagementEmailingQueryError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>


export function useGetApiSettingManagementEmailing<TData = Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementEmailing>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementEmailing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettingManagementEmailing<TData = Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiSettingManagementEmailing>>,
          TError,
          Awaited<ReturnType<typeof getApiSettingManagementEmailing>>
        > , 'initialData'
      >, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiSettingManagementEmailing<TData = Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiSettingManagementEmailing<TData = Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiSettingManagementEmailing>>, TError, TData>>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiSettingManagementEmailingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getPostApiSettingManagementEmailingUrl = () => {




  return `/api/setting-management/emailing`
}

export const postApiSettingManagementEmailing = async (voloAbpSettingManagementUpdateEmailSettingsDto?: VoloAbpSettingManagementUpdateEmailSettingsDto, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<void>(getPostApiSettingManagementEmailingUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpSettingManagementUpdateEmailSettingsDto)
  }
);}





export const getPostApiSettingManagementEmailingMutationKey = () => ['postApiSettingManagementEmailing'] as const;

export const getPostApiSettingManagementEmailingMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailing>>, TError,PostApiSettingManagementEmailingMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailing>>, TError,PostApiSettingManagementEmailingMutationVariables, TContext> => {

const mutationKey = getPostApiSettingManagementEmailingMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSettingManagementEmailing>>, PostApiSettingManagementEmailingMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiSettingManagementEmailing(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSettingManagementEmailingMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSettingManagementEmailing>>>
    export type PostApiSettingManagementEmailingMutationBody = VoloAbpSettingManagementUpdateEmailSettingsDto | undefined
    export type PostApiSettingManagementEmailingMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiSettingManagementEmailingMutationVariables = {data?: VoloAbpSettingManagementUpdateEmailSettingsDto}

    export const usePostApiSettingManagementEmailing = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailing>>, TError,PostApiSettingManagementEmailingMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSettingManagementEmailing>>,
        TError,
        PostApiSettingManagementEmailingMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiSettingManagementEmailingMutationOptions(options), queryClient);
    }
    export const getPostApiSettingManagementEmailingSendTestEmailUrl = () => {




  return `/api/setting-management/emailing/send-test-email`
}

export const postApiSettingManagementEmailingSendTestEmail = async (voloAbpSettingManagementSendTestEmailInput?: VoloAbpSettingManagementSendTestEmailInput, options?: Parameters<typeof abpMutator>[1]): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return abpMutator<void>(getPostApiSettingManagementEmailingSendTestEmailUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(voloAbpSettingManagementSendTestEmailInput)
  }
);}





export const getPostApiSettingManagementEmailingSendTestEmailMutationKey = () => ['postApiSettingManagementEmailingSendTestEmail'] as const;

export const getPostApiSettingManagementEmailingSendTestEmailMutationOptions = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>, TError,PostApiSettingManagementEmailingSendTestEmailMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>, TError,PostApiSettingManagementEmailingSendTestEmailMutationVariables, TContext> => {

const mutationKey = getPostApiSettingManagementEmailingSendTestEmailMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>, PostApiSettingManagementEmailingSendTestEmailMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postApiSettingManagementEmailingSendTestEmail(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiSettingManagementEmailingSendTestEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>>
    export type PostApiSettingManagementEmailingSendTestEmailMutationBody = VoloAbpSettingManagementSendTestEmailInput | undefined
    export type PostApiSettingManagementEmailingSendTestEmailMutationError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>
    export type PostApiSettingManagementEmailingSendTestEmailMutationVariables = {data?: VoloAbpSettingManagementSendTestEmailInput}

    export const usePostApiSettingManagementEmailingSendTestEmail = <TError = ErrorType<VoloAbpHttpRemoteServiceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>, TError,PostApiSettingManagementEmailingSendTestEmailMutationVariables, TContext>, request?: SecondParameter<typeof abpMutator>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiSettingManagementEmailingSendTestEmail>>,
        TError,
        PostApiSettingManagementEmailingSendTestEmailMutationVariables,
        TContext
      > => {
      return useMutation(getPostApiSettingManagementEmailingSendTestEmailMutationOptions(options), queryClient);
    }
