/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const postApiAccountRegisterBodyUserNameMin = 0;
export const postApiAccountRegisterBodyUserNameMax = 256;

export const postApiAccountRegisterBodyEmailAddressMin = 0;
export const postApiAccountRegisterBodyEmailAddressMax = 256;

export const postApiAccountRegisterBodyPasswordMin = 0;
export const postApiAccountRegisterBodyPasswordMax = 128;




export const postApiAccountRegisterBody = zod.object({
  "userName": zod.string().min(postApiAccountRegisterBodyUserNameMin).max(postApiAccountRegisterBodyUserNameMax),
  "emailAddress": zod.email().min(postApiAccountRegisterBodyEmailAddressMin).max(postApiAccountRegisterBodyEmailAddressMax),
  "password": zod.string().min(postApiAccountRegisterBodyPasswordMin).max(postApiAccountRegisterBodyPasswordMax),
  "appName": zod.string().min(1)
})

export const postApiAccountRegisterResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "id": zod.uuid().optional(),
  "creationTime": zod.iso.datetime({}).optional(),
  "creatorId": zod.uuid().nullish(),
  "lastModificationTime": zod.iso.datetime({}).nullish(),
  "lastModifierId": zod.uuid().nullish(),
  "isDeleted": zod.boolean().optional(),
  "deleterId": zod.uuid().nullish(),
  "deletionTime": zod.iso.datetime({}).nullish(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "isActive": zod.boolean().optional(),
  "lockoutEnabled": zod.boolean().optional(),
  "accessFailedCount": zod.number().optional(),
  "lockoutEnd": zod.iso.datetime({}).nullish(),
  "concurrencyStamp": zod.string().nullish(),
  "entityVersion": zod.number().optional(),
  "lastPasswordChangeTime": zod.iso.datetime({}).nullish()
})

export const postApiAccountSendPasswordResetCodeBodyEmailMin = 0;
export const postApiAccountSendPasswordResetCodeBodyEmailMax = 256;




export const postApiAccountSendPasswordResetCodeBody = zod.object({
  "email": zod.email().min(postApiAccountSendPasswordResetCodeBodyEmailMin).max(postApiAccountSendPasswordResetCodeBodyEmailMax),
  "appName": zod.string().min(1),
  "returnUrl": zod.string().nullish(),
  "returnUrlHash": zod.string().nullish()
})




export const postApiAccountVerifyPasswordResetTokenBody = zod.object({
  "userId": zod.uuid().optional(),
  "resetToken": zod.string().min(1)
})

export const postApiAccountVerifyPasswordResetTokenResponse = zod.boolean()





export const postApiAccountResetPasswordBody = zod.object({
  "userId": zod.uuid().optional(),
  "resetToken": zod.string().min(1),
  "password": zod.string().min(1)
})

