/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutAuthedRouteImport } from './routes/_layout/_authed'
import { Route as LayoutForbiddenRouteImport } from './routes/_layout/forbidden'
import { Route as ApiCultureRouteImport } from './routes/api.culture'
import { Route as ApiTenantRouteImport } from './routes/api.tenant'
import { Route as LayoutAuthedHomeRouteImport } from './routes/_layout/_authed/home'
import { Route as ApiAuthCallbackRouteImport } from './routes/api.auth.callback'
import { Route as ApiAuthLoginRouteImport } from './routes/api.auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api.auth.logout'
import { Route as LayoutAuthedBooksIndexRouteImport } from './routes/_layout/_authed/books/index'
import { Route as LayoutAuthedBooksNewRouteImport } from './routes/_layout/_authed/books/new'
import { Route as LayoutAuthedIdentityRolesRouteImport } from './routes/_layout/_authed/identity/roles'
import { Route as LayoutAuthedIdentityUsersRouteImport } from './routes/_layout/_authed/identity/users'
import { Route as LayoutAuthedProfileIndexRouteImport } from './routes/_layout/_authed/profile/index'
import { Route as LayoutAuthedSettingsIndexRouteImport } from './routes/_layout/_authed/settings/index'
import { Route as LayoutAuthedTenantsIndexRouteImport } from './routes/_layout/_authed/tenants/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedRoute = LayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutForbiddenRoute = LayoutForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiCultureRoute = ApiCultureRouteImport.update({
  id: '/api/culture',
  path: '/api/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTenantRoute = ApiTenantRouteImport.update({
  id: '/api/tenant',
  path: '/api/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedHomeRoute = LayoutAuthedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const ApiAuthCallbackRoute = ApiAuthCallbackRouteImport.update({
  id: '/api/auth/callback',
  path: '/api/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutAuthedBooksIndexRoute = LayoutAuthedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedBooksNewRoute = LayoutAuthedBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => LayoutAuthedRoute,
} as any)
const LayoutAuthedIdentityRolesRoute =
  LayoutAuthedIdentityRolesRouteImport.update({
    id: '/identity/roles',
    path: '/identity/roles',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedIdentityUsersRoute =
  LayoutAuthedIdentityUsersRouteImport.update({
    id: '/identity/users',
    path: '/identity/users',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedProfileIndexRoute =
  LayoutAuthedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedSettingsIndexRoute =
  LayoutAuthedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)
const LayoutAuthedTenantsIndexRoute =
  LayoutAuthedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => LayoutAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof LayoutForbiddenRoute
  '/api/culture': typeof ApiCultureRoute
  '/api/tenant': typeof ApiTenantRoute
  '/home': typeof LayoutAuthedHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/books/new': typeof LayoutAuthedBooksNewRoute
  '/identity/roles': typeof LayoutAuthedIdentityRolesRoute
  '/identity/users': typeof LayoutAuthedIdentityUsersRoute
  '/books/': typeof LayoutAuthedBooksIndexRoute
  '/profile/': typeof LayoutAuthedProfileIndexRoute
  '/settings/': typeof LayoutAuthedSettingsIndexRoute
  '/tenants/': typeof LayoutAuthedTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/forbidden': typeof LayoutForbiddenRoute
  '/api/culture': typeof ApiCultureRoute
  '/api/tenant': typeof ApiTenantRoute
  '/home': typeof LayoutAuthedHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/books/new': typeof LayoutAuthedBooksNewRoute
  '/identity/roles': typeof LayoutAuthedIdentityRolesRoute
  '/identity/users': typeof LayoutAuthedIdentityUsersRoute
  '/books': typeof LayoutAuthedBooksIndexRoute
  '/profile': typeof LayoutAuthedProfileIndexRoute
  '/settings': typeof LayoutAuthedSettingsIndexRoute
  '/tenants': typeof LayoutAuthedTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/_authed': typeof LayoutAuthedRouteWithChildren
  '/_layout/forbidden': typeof LayoutForbiddenRoute
  '/api/culture': typeof ApiCultureRoute
  '/api/tenant': typeof ApiTenantRoute
  '/_layout/_authed/home': typeof LayoutAuthedHomeRoute
  '/api/auth/callback': typeof ApiAuthCallbackRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/_layout/_authed/books/new': typeof LayoutAuthedBooksNewRoute
  '/_layout/_authed/identity/roles': typeof LayoutAuthedIdentityRolesRoute
  '/_layout/_authed/identity/users': typeof LayoutAuthedIdentityUsersRoute
  '/_layout/_authed/books/': typeof LayoutAuthedBooksIndexRoute
  '/_layout/_authed/profile/': typeof LayoutAuthedProfileIndexRoute
  '/_layout/_authed/settings/': typeof LayoutAuthedSettingsIndexRoute
  '/_layout/_authed/tenants/': typeof LayoutAuthedTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/forbidden'
    | '/api/culture'
    | '/api/tenant'
    | '/home'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/books/new'
    | '/identity/roles'
    | '/identity/users'
    | '/books/'
    | '/profile/'
    | '/settings/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forbidden'
    | '/api/culture'
    | '/api/tenant'
    | '/home'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/books/new'
    | '/identity/roles'
    | '/identity/users'
    | '/books'
    | '/profile'
    | '/settings'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/_layout/_authed'
    | '/_layout/forbidden'
    | '/api/culture'
    | '/api/tenant'
    | '/_layout/_authed/home'
    | '/api/auth/callback'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/_layout/_authed/books/new'
    | '/_layout/_authed/identity/roles'
    | '/_layout/_authed/identity/users'
    | '/_layout/_authed/books/'
    | '/_layout/_authed/profile/'
    | '/_layout/_authed/settings/'
    | '/_layout/_authed/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCultureRoute: typeof ApiCultureRoute
  ApiTenantRoute: typeof ApiTenantRoute
  ApiAuthCallbackRoute: typeof ApiAuthCallbackRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed': {
      id: '/_layout/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/forbidden': {
      id: '/_layout/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof LayoutForbiddenRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/culture': {
      id: '/api/culture'
      path: '/api/culture'
      fullPath: '/api/culture'
      preLoaderRoute: typeof ApiCultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tenant': {
      id: '/api/tenant'
      path: '/api/tenant'
      fullPath: '/api/tenant'
      preLoaderRoute: typeof ApiTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/home': {
      id: '/_layout/_authed/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthedHomeRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/api/auth/callback': {
      id: '/api/auth/callback'
      path: '/api/auth/callback'
      fullPath: '/api/auth/callback'
      preLoaderRoute: typeof ApiAuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_authed/books/': {
      id: '/_layout/_authed/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof LayoutAuthedBooksIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/books/new': {
      id: '/_layout/_authed/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof LayoutAuthedBooksNewRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/identity/roles': {
      id: '/_layout/_authed/identity/roles'
      path: '/identity/roles'
      fullPath: '/identity/roles'
      preLoaderRoute: typeof LayoutAuthedIdentityRolesRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/identity/users': {
      id: '/_layout/_authed/identity/users'
      path: '/identity/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof LayoutAuthedIdentityUsersRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/profile/': {
      id: '/_layout/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutAuthedProfileIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/settings/': {
      id: '/_layout/_authed/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
    '/_layout/_authed/tenants/': {
      id: '/_layout/_authed/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof LayoutAuthedTenantsIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
  }
}

interface LayoutAuthedRouteChildren {
  LayoutAuthedHomeRoute: typeof LayoutAuthedHomeRoute
  LayoutAuthedBooksNewRoute: typeof LayoutAuthedBooksNewRoute
  LayoutAuthedIdentityRolesRoute: typeof LayoutAuthedIdentityRolesRoute
  LayoutAuthedIdentityUsersRoute: typeof LayoutAuthedIdentityUsersRoute
  LayoutAuthedBooksIndexRoute: typeof LayoutAuthedBooksIndexRoute
  LayoutAuthedProfileIndexRoute: typeof LayoutAuthedProfileIndexRoute
  LayoutAuthedSettingsIndexRoute: typeof LayoutAuthedSettingsIndexRoute
  LayoutAuthedTenantsIndexRoute: typeof LayoutAuthedTenantsIndexRoute
}

const LayoutAuthedRouteChildren: LayoutAuthedRouteChildren = {
  LayoutAuthedHomeRoute: LayoutAuthedHomeRoute,
  LayoutAuthedBooksNewRoute: LayoutAuthedBooksNewRoute,
  LayoutAuthedIdentityRolesRoute: LayoutAuthedIdentityRolesRoute,
  LayoutAuthedIdentityUsersRoute: LayoutAuthedIdentityUsersRoute,
  LayoutAuthedBooksIndexRoute: LayoutAuthedBooksIndexRoute,
  LayoutAuthedProfileIndexRoute: LayoutAuthedProfileIndexRoute,
  LayoutAuthedSettingsIndexRoute: LayoutAuthedSettingsIndexRoute,
  LayoutAuthedTenantsIndexRoute: LayoutAuthedTenantsIndexRoute,
}

const LayoutAuthedRouteWithChildren = LayoutAuthedRoute._addFileChildren(
  LayoutAuthedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthedRoute: typeof LayoutAuthedRouteWithChildren
  LayoutForbiddenRoute: typeof LayoutForbiddenRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthedRoute: LayoutAuthedRouteWithChildren,
  LayoutForbiddenRoute: LayoutForbiddenRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCultureRoute: ApiCultureRoute,
  ApiTenantRoute: ApiTenantRoute,
  ApiAuthCallbackRoute: ApiAuthCallbackRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
