/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAbpApplicationLocalizationQueryParams = zod.object({
  "CultureName": zod.string(),
  "OnlyDynamics": zod.boolean().optional()
})

export const getApiAbpApplicationLocalizationResponse = zod.object({
  "resources": zod.record(zod.string(), zod.object({
  "texts": zod.record(zod.string(), zod.string()).nullish(),
  "baseResources": zod.array(zod.string()).nullish()
})).nullish(),
  "currentCulture": zod.object({
  "displayName": zod.string().nullish(),
  "englishName": zod.string().nullish(),
  "threeLetterIsoLanguageName": zod.string().nullish(),
  "twoLetterIsoLanguageName": zod.string().nullish(),
  "isRightToLeft": zod.boolean().optional(),
  "cultureName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "nativeName": zod.string().nullish(),
  "dateTimeFormat": zod.object({
  "calendarAlgorithmType": zod.string().nullish(),
  "dateTimeFormatLong": zod.string().nullish(),
  "shortDatePattern": zod.string().nullish(),
  "fullDateTimePattern": zod.string().nullish(),
  "dateSeparator": zod.string().nullish(),
  "shortTimePattern": zod.string().nullish(),
  "longTimePattern": zod.string().nullish()
}).optional()
}).optional()
})

