/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiAccountMyProfileResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "userName": zod.string().nullish(),
  "email": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "isExternal": zod.boolean().optional(),
  "hasPassword": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish()
})

export const putApiAccountMyProfileBodyUserNameMin = 0;
export const putApiAccountMyProfileBodyUserNameMax = 256;

export const putApiAccountMyProfileBodyEmailMin = 0;
export const putApiAccountMyProfileBodyEmailMax = 256;

export const putApiAccountMyProfileBodyNameMin = 0;
export const putApiAccountMyProfileBodyNameMax = 64;

export const putApiAccountMyProfileBodySurnameMin = 0;
export const putApiAccountMyProfileBodySurnameMax = 64;

export const putApiAccountMyProfileBodyPhoneNumberMin = 0;
export const putApiAccountMyProfileBodyPhoneNumberMax = 16;



export const PutApiAccountMyProfileBody = zod.object({
  "userName": zod.string().min(putApiAccountMyProfileBodyUserNameMin).max(putApiAccountMyProfileBodyUserNameMax).nullish(),
  "email": zod.string().min(putApiAccountMyProfileBodyEmailMin).max(putApiAccountMyProfileBodyEmailMax).nullish(),
  "name": zod.string().min(putApiAccountMyProfileBodyNameMin).max(putApiAccountMyProfileBodyNameMax).nullish(),
  "surname": zod.string().min(putApiAccountMyProfileBodySurnameMin).max(putApiAccountMyProfileBodySurnameMax).nullish(),
  "phoneNumber": zod.string().min(putApiAccountMyProfileBodyPhoneNumberMin).max(putApiAccountMyProfileBodyPhoneNumberMax).nullish(),
  "concurrencyStamp": zod.string().nullish()
})

export const PutApiAccountMyProfileResponse = zod.object({
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish(),
  "userName": zod.string().nullish(),
  "email": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "phoneNumber": zod.string().nullish(),
  "isExternal": zod.boolean().optional(),
  "hasPassword": zod.boolean().optional(),
  "concurrencyStamp": zod.string().nullish()
})

export const postApiAccountMyProfileChangePasswordBodyCurrentPasswordMin = 0;
export const postApiAccountMyProfileChangePasswordBodyCurrentPasswordMax = 128;

export const postApiAccountMyProfileChangePasswordBodyNewPasswordMin = 0;
export const postApiAccountMyProfileChangePasswordBodyNewPasswordMax = 128;



export const PostApiAccountMyProfileChangePasswordBody = zod.object({
  "currentPassword": zod.string().min(postApiAccountMyProfileChangePasswordBodyCurrentPasswordMin).max(postApiAccountMyProfileChangePasswordBodyCurrentPasswordMax).nullish(),
  "newPassword": zod.string().min(postApiAccountMyProfileChangePasswordBodyNewPasswordMin).max(postApiAccountMyProfileChangePasswordBodyNewPasswordMax)
})

export const PostApiAccountMyProfileChangePasswordResponse = zod.unknown()

