/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiIdentityUsersLookupIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiIdentityUsersLookupIdResponse = zod.object({
  "id": zod.uuid().optional(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "isActive": zod.boolean().optional(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish()
})

export const GetApiIdentityUsersLookupByUsernameUserNameParams = zod.object({
  "userName": zod.string()
})

export const GetApiIdentityUsersLookupByUsernameUserNameResponse = zod.object({
  "id": zod.uuid().optional(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "isActive": zod.boolean().optional(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish()
})

export const getApiIdentityUsersLookupSearchQuerySkipCountMin = 0;
export const getApiIdentityUsersLookupSearchQuerySkipCountMax = 2147483647;

export const getApiIdentityUsersLookupSearchQueryMaxResultCountMax = 2147483647;



export const GetApiIdentityUsersLookupSearchQueryParams = zod.object({
  "Filter": zod.string().optional(),
  "Sorting": zod.string().optional(),
  "SkipCount": zod.int().min(getApiIdentityUsersLookupSearchQuerySkipCountMin).max(getApiIdentityUsersLookupSearchQuerySkipCountMax).optional(),
  "MaxResultCount": zod.int().min(1).max(getApiIdentityUsersLookupSearchQueryMaxResultCountMax).optional(),
  "ExtraProperties": zod.record(zod.string(), zod.unknown()).optional()
})

export const GetApiIdentityUsersLookupSearchResponse = zod.object({
  "items": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "tenantId": zod.uuid().nullish(),
  "userName": zod.string().nullish(),
  "name": zod.string().nullish(),
  "surname": zod.string().nullish(),
  "isActive": zod.boolean().optional(),
  "email": zod.string().nullish(),
  "emailConfirmed": zod.boolean().optional(),
  "phoneNumber": zod.string().nullish(),
  "phoneNumberConfirmed": zod.boolean().optional(),
  "extraProperties": zod.record(zod.string(), zod.unknown()).nullish()
})).nullish()
})

export const GetApiIdentityUsersLookupCountQueryParams = zod.object({
  "Filter": zod.string().optional()
})

export const GetApiIdentityUsersLookupCountResponse = zod.int()

