/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const GetApiAbpMultiTenancyTenantsByNameNameParams = zod.object({
  "name": zod.string()
})

export const GetApiAbpMultiTenancyTenantsByNameNameResponse = zod.object({
  "success": zod.boolean().optional(),
  "tenantId": zod.uuid().nullish(),
  "name": zod.string().nullish(),
  "normalizedName": zod.string().nullish(),
  "isActive": zod.boolean().optional()
})

export const GetApiAbpMultiTenancyTenantsByIdIdParams = zod.object({
  "id": zod.uuid()
})

export const GetApiAbpMultiTenancyTenantsByIdIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "tenantId": zod.uuid().nullish(),
  "name": zod.string().nullish(),
  "normalizedName": zod.string().nullish(),
  "isActive": zod.boolean().optional()
})

