/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * AbpSwagger API
 * OpenAPI spec version: v1
 */
import * as zod from 'zod';


export const getApiAbpMultiTenancyTenantsByNameNameParams = zod.object({
  "name": zod.string()
})

export const getApiAbpMultiTenancyTenantsByNameNameResponse = zod.object({
  "success": zod.boolean().optional(),
  "tenantId": zod.uuid().nullish(),
  "name": zod.string().nullish(),
  "normalizedName": zod.string().nullish(),
  "isActive": zod.boolean().optional()
})

export const getApiAbpMultiTenancyTenantsByIdIdParams = zod.object({
  "id": zod.uuid()
})

export const getApiAbpMultiTenancyTenantsByIdIdResponse = zod.object({
  "success": zod.boolean().optional(),
  "tenantId": zod.uuid().nullish(),
  "name": zod.string().nullish(),
  "normalizedName": zod.string().nullish(),
  "isActive": zod.boolean().optional()
})

